# GFWList: GFWList4LL
# Updated: Tue, 29 Jan 2019 08:22:38 -0500
{+forward-override{forward-socks5 127.0.0.1:9050 .}}
*2.bahamut.com.tw:80
.030buy.com:80
.0rz.tw:80
.1-apple.com.tw
.1.1.1.1
.10.tt:80
.1000giri.net
.100ke.org:80
.10conditionsoflove.com:80
.10musume.com
.12bet.com
.12vpn.com
.12vpn.net
.138.com:80
.141jj.com
.141tube.com:80
.1688.com.au:80
.173ng.com
.177pic.info:80
.17t17p.com:80
.18board.com
.18board.info
.18p2p.com:80
.18virginsex.com:80
.1949er.org:80
.1984bbs.com
.1984bbs.org
.1991way.com
.1998cdp.org:80
.1bao.org:80
.1dumb.com:80
.1e100.net
.1eew.com:80
.1mobile.com:80
.1mobile.tw:80
.1pondo.tv
.2-hand.info:80
.2008xianzhang.info
.2017.hk
.21pron.com:80
.228.net.tw:80
.233abc.com
.24hrs.ca
.25u.com:80
.2shared.com:80
.2waky.com:80
.3-a.net:80
.315lz.com:80
.32red.com
.36rain.com
.3a5a.com:80
.3boys2girls.com:80
.3d-game.com:80
.3proxy.ru:80
.3ren.ca:80
.3tui.net:80
.43110.cf
.466453.com
.4bluestones.biz
.4chan.com:80
.4dq.com:80
.4everproxy.com
.4irc.com:80
.4mydomain.com:80
.4pu.com:80
.4rbtv.com
.4shared.com
.51.ca
.51jav.org
.51luoben.com
.5278.cc:80
.5299.tv:80
.5isotoi5.org:80
.5maodang.com:80
.63i.com
.64museum.org:80
.66.ca:80
.6park.com
.6parker.com
.7capture.com
.7cow.com:80
.8-d.com:80
.85cc.us:80
.881903.com
.888.com:80
.888poker.com:80
.89-64.org
.8news.com.tw:80
.8z1.net
.9001700.com:80
.91porn.com
.91vps.club
.92ccav.com:80
.991.com:80
.99btgc01.com
.99cn.info:80
.9bis.com
.9bis.net
.a-normal-day.com
.a248.e.akamai.net
.abc.com:80
.abc.net.au
.abc.pp.ru
.abc.xyz
.abchinese.com:80
.abebooks.com
.abematv.akamaized.net
.ablwang.com:80
.aboluowang.com
.aboutgfw.com:80
.abs.edu:80
.accim.org:80
.aceros-de-hispania.com:80
.acevpn.com
.acg18.me:80
.acgkj.com
.acmedia365.com:80
.acmetoy.com:80
.acnw.com.au:80
.activpn.com
.aculo.us
.adcex.com
.addictedtocoffee.de
.admin.recaptcha.net
.admob.com
.adpl.org.hk:80
.ads-twitter.com
.adsense.com
.adult-sex-games.com
.advanscene.com
.advertfan.com
.ae.org:80
.aenhancers.com
.aex.com
.af.mil
.afantibbs.com:80
.agnesb.fr
.agoogleaday.com
.agro.hk
.ai-kan.net
.ai.google
.aiph.net
.airasia.com:80
.airconsole.com
.airvpn.org
.aisex.com:80
.ait.org.tw
.aiweiweiblog.com
.akiba-online.com
.akiba-web.com
.akow.org
.al-islam.com:80
.al-qimmah.net
.alabout.com
.alanhou.com:80
.alarab.qa:80
.alasbarricadas.org
.alforattv.net
.alhayat.com:80
.alicejapan.co.jp:80
.alkasir.com
.allcoin.com
.allconnected.co
.alldrawnsex.com
.allervpn.com:80
.allfinegirls.com
.allgirlmassage.com:80
.allgravure.com:80
.allinfa.com:80
.alljackpotscasino.com:80
.allmovie.com
.allowed.org:80
.almasdarnews.com
.almostmy.com:80
.alphaporno.com:80
.alternate-tools.com
.altrec.com
.alwaysdata.com
.alwaysdata.net
.alwaysvpn.com
.am730.com.hk
.amazon.co.jp
.ameblo.jp
.americangreencard.com
.americanunfinished.com:80
.amiblockedornot.com
.amigobbs.net:80
.amitabhafoundation.us:80
.amnesty.org
.amnesty.org.hk
.amnesty.tw:80
.amnestyusa.org
.amnyemachen.org:80
.amoiist.com:80
.ampproject.org
.amtb-taipei.org:80
.anchorfree.com
.ancsconf.org
.andfaraway.net
.android-x86.org
.android.com
.androidify.com
.androidtv.com
.andygod.com:80
.angela-merkel.de
.angola.org
.angularjs.org
.animeshippuuden.com:80
.aniscartujo.com
.anobii.com
.anonymitynetwork.com:80
.anonymizer.com:80
.anpopo.com:80
.answering-islam.org:80
.anthonycalzadilla.com
.anti1984.com:80
.antiwave.net:80
.anyporn.com:80
.anysex.com:80
.aobo.com.au
.aofriend.com.au:80
.aofriend.com:80
.aojiao.org:80
.aolchannels.aol.com
.aomiwang.com
.apartmentratings.com
.apartments.com
.apetube.com:80
.api-secure.recaptcha.net
.api-verify.recaptcha.net
.api.ai
.api.dropboxapi.com
.api.linksalpha.com
.api.pureapk.com
.api.recaptcha.net
.apiary.io
.apidocs.linksalpha.com
.apigee.com
.apkmirror.com
.apkplz.com
.apkpure.com
.aplusvpn.com:80
.app.box.com
.app.smartmailcloud.com
.app.tutanota.com
.appledaily.com
.appledaily.com.hk
.appledaily.com.tw
.appshopper.com:80
.appsocks.net
.appspot.com
.appsto.re
.aptoide.com
.archive.fo
.archive.is
.archive.li
.archive.org
.archives.gov
.archives.gov.tw
.arctosia.com:80
.areca-backup.org
.arena.taipei
.arethusa.su
.arlingtoncemetery.mil
.army.mil
.art4tibet1998.org:80
.arte.tv
.asacp.org
.asia-gaming.com:80
.asiaharvest.org
.asiansexdiary.com
.asianspiss.com
.asianwomensfilm.de
.asiatgp.com:80
.asiatoday.us:80
.askstudent.com
.askynz.net
.assembla.com
.assets.bwbx.io
.assimp.org
.astrill.com
.atc.org.au
.atchinese.com:80
.atdmt.com
.athenaeizou.com
.atlaspost.com
.atnext.com
.authorizeddns.net:80
.authorizeddns.org:80
.authorizeddns.us:80
.autodraw.com
.av-e-body.com:80
.av.com:80
.av.movie
.avaaz.org
.avbody.tv:80
.avcity.tv:80
.avcool.com:80
.avdb.in
.avdb.tv
.avfantasy.com:80
.avgle.com
.avidemux.org
.avmo.pw:80
.avmoo.com:80
.avmoo.net:80
.avmoo.pw
.avoision.com
.avyahoo.com:80
.axureformac.com
.azerbaycan.tv:80
.azubu.tv
.b0ne.com:80
.backchina.com
.badiucao.com
.badjojo.com:80
.baidu.jp
.baijie.org:80
.bailandaily.com
.baixing.me
.bakgeekhome.tk
.banana-vpn.com
.band.us:80
.bandwagonhost.com
.bangbrosnetwork.com:80
.bangchen.net:80
.bangdream.space
.bangyoulater.com
.bankmobilevibe.com
.bannedbook.org
.bannednews.org:80
.banorte.com
.baramangaonline.com:80
.barenakedislam.com:80
.barnabu.co.uk
.bash-hackers.org
.bastillepost.com:80
.bayvoice.net
.bb-chat.tv
.bbc.co.uk
.bbc.com
.bbcchinese.com
.bbchat.tv
.bbci.co.uk
.bbg.gov:80
.bbnradio.org:80
.bbs.junglobal.net
.bbs.mychat.to
.bbsfeed.com
.bbsmo.com:80
.bbsone.com:80
.bcast.co.nz:80
.bcchinese.net:80
.bcex.ca
.bcmorning.com:80
.beaconevents.com:80
.bebo.com
.beeg.com
.beevpn.com
.behance.net
.behindkink.com:80
.beijing1989.com
.beijingspring.com
.beijingzx.org:80
.belamionline.com:80
.bell.wiki:80
.berlintwitterwall.com
.berm.co.nz:80
.bestforchina.org
.bestgore.com:80
.bestpornstardb.com:80
.bestvpn.com
.bestvpnanalysis.com:80
.bestvpnserver.com:80
.bestvpnservice.com:80
.bestvpnusa.com:80
.bet365.com
.betfair.com:80
.betternet.co
.bettervpn.com
.bettween.com
.betvictor.com
.bewww.net:80
.beyondfirewall.com:80
.bfnn.org
.bfsh.hk
.bgvpn.com
.bianlei.com:80
.biblesforamerica.org:80
.bibox.com
.bic2011.org:80
.big.one
.bigjapanesesex.com
.bigmoney.biz:80
.bignews.org
.bigsound.org:80
.biliworld.com:80
.binance.com
.binux.me:80
.bird.so
.bit-z.com
.bit.do:80
.bit.ly:80
.bitcointalk.org
.bitcoinworld.com
.bitfinex.com
.bithumb.com
.bitinka.com.ar
.bitmex.com
.bitshare.com
.bitvise.com
.bjnewlife.org:80
.bjs.org:80
.bjzc.org
.bl-doujinsouko.com
.blacklogic.com:80
.blackvpn.com
.blinkx.com
.blip.tv
.blockcn.com
.blockless.com
.blog.de
.blog.exblog.co.jp
.blog.expofutures.com
.blog.fizzik.com
.blog.fuckgfw233.org
.blog.google
.blog.jp:80
.blog.kangye.org
.blog.pathtosharepoint.com
.blog.pentalogic.net
.blog.tiney.com
.blogblog.com
.blogcatalog.com
.blogcity.me
.blogdns.org:80
.blogger.com
.bloglines.com
.bloglovin.com
.blogs.tampabay.com
.blogspot.*
.blogspot.hk:80
.blogspot.jp:80
.blogspot.tw:80
.blogtd.org:80
.bloodshed.net
.bloomberg.cn
.bloomberg.com
.bloomberg.de
.bloombergview.com
.bloomfortune.com
.bmfinn.com:80
.bnews.co
.bnn.co
.bnrmetal.com
.boardreader.com
.bod.asia:80
.bodog88.com:80
.bolehvpn.net
.bonbonsex.com:80
.bonfoundation.org:80
.bongacams.com:80
.boobstagram.com
.book.com.tw
.books.com.tw
.booktopia.com.au
.boomssr.com
.bot.nu:80
.botanwang.com
.bowenpress.com
.boxpn.com
.boxun*.azurewebsites.net
.boxun.com
.boxun.tv
.boxunblog.com
.boxunclub.com:80
.boyfriendtv.com:80
.boysfood.com:80
.boysmaster.com
.br.st
.brandonhutchinson.com
.braumeister.org
.bravotube.net
.brazzers.com
.break.com
.breakgfw.com
.breakingtweets.com
.breakwall.net
.brizzly.com
.brkmd.com
.broadpressinc.com
.brutaltgp.com
.bt2mag.com:80
.bt95.com
.btaia.com:80
.btbtav.com:80
.btc98.com
.btcbank.bank
.btctrade.im
.btku.me
.btku.org
.btspread.com:80
.btsynckeys.com:80
.budaedu.org
.buddhistchannel.tv:80
.buffered.com:80
.bullog.org
.bullogger.com
.busayari.com:80
.businessinsider.com
.businessweek.com:80
.buugaa.com:80
.buzzhand.com:80
.buzzhand.net:80
.buzzorange.com
.bvpn.com
.bwgyhw.com
.bwh1.net
.bx.in.th
.bx.tl
.bynet.co.il
.c-est-simple.com
.c-spanvideo.org
.c100tibet.org:80
.c2cx.com
.cablegatesearch.net
.cachinese.com:80
.cacnw.com:80
.cactusvpn.com
.cafepress.com:80
.cahr.org.tw:80
.calebelston.com
.calgarychinese.ca:80
.calgarychinese.com:80
.calgarychinese.net:80
.cam4.com:80
.cam4.jp:80
.cam4.sg:80
.camfrog.com
.cams.com
.cams.org.sg:80
.canalporno.com:80
.canyu.org
.cao.im:80
.caobian.info
.caochangqing.com
.cap.org.hk
.carabinasypistolas.com:80
.carfax.com
.caribbeancom.com
.cartoonmovement.com
.casadeltibetbcn.org:80
.casatibet.org.mx:80
.casino.williamhill.com
.casinobellini.com
.casinoking.com:80
.casinoriva.com:80
.castbox.fm
.catch22.net
.catchgod.com:80
.catfightpayperview.xxx
.catholic.org.hk
.catholic.org.tw
.cathvoice.org.tw:80
.cattt.com
.cbc.ca
.cbs.ntu.edu.tw
.cbtc.org.hk:80
.cccat.cc
.cccat.co
.ccdtr.org
.cchere.com
.ccim.org:80
.cclife.ca:80
.ccthere.com
.ccthere.net
.cctmweb.net:80
.ccvoice.ca:80
.ccw.org.tw:80
.cdbook.org
.cdcparty.com:80
.cdef.org
.cdig.info
.cdjp.org
.cdn*.i-scmp.com
.cdn-apple.com
.cdn-images.mailchimp.com
.cdn.assets.lfpcontent.com
.cdn.helixstudios.net
.cdn.printfriendly.com
.cdn.seatguru.com
.cdn.softlayer.net
.cdnews.com.tw:80
.cdninstagram.com
.cdp1998.org
.cdp2006.org
.cdpa.url.tw:80
.cdpweb.org
.cdpwu.org
.cdw.com
.cecc.gov
.cellulo.info
.cenews.eu
.centauro.com.br
.centerforhumanreprod.com
.centralnation.com
.centurys.net:80
.certificate-transparency.org
.cfhks.org.hk:80
.cfos.de:80
.cftfc.com:80
.cgdepot.org:80
.cgst.edu:80
.change.org
.changeip.name:80
.changeip.net:80
.changeip.org:80
.changp.com
.changsa.net:80
.chaoex.com
.chapm25.com:80
.chatnook.com:80
.chaturbate.com:80
.chenguangcheng.com
.chenpokong.com:80
.chenpokong.net:80
.chenshan20042005.wordpress.com
.cherrysave.com
.chhongbi.org:80
.china-mmm.net
.china-review.com.ua:80
.china-week.com:80
.china101.com
.china18.org
.china21.com
.china21.org
.china5000.us:80
.chinaaffairs.org
.chinaaid.me
.chinachange.org
.chinachannel.hk
.chinacitynews.be:80
.chinacomments.org
.chinadialogue.net:80
.chinadigitaltimes.net
.chinaelections.org
.chinaeweekly.com
.chinafreepress.org
.chinagate.com:80
.chinagfw.org
.chinagonet.com:80
.chinagreenparty.org
.chinahorizon.org
.chinahush.com:80
.chinainperspective.com:80
.chinainterimgov.org
.chinamule.com
.chinapress.com.my
.chinarightsia.org:80
.chinasocialdemocraticparty.com
.chinasoul.org
.chinasucks.net:80
.chinatopsex.com
.chinatown.com.au:80
.chinaview.wordpress.com
.chinaworker.info
.chinayuanmin.org
.chinese-hermit.net:80
.chinesedaily.com:80
.chinesedailynews.com
.chinesedemocracy.com
.chinesegay.org
.chinesen.de
.chinesenews.net.au:80
.chinesepen.org:80
.chineseupress.com
.chingcheong.com
.chinman.net:80
.chobit.cc
.chrdnet.com:80
.christianfreedom.org:80
.christianstudy.com
.chrlawyers.hk:80
.chrome.com
.chromecast.com
.chromeexperiments.com
.chromercise.com
.chromestatus.com
.chromium.org
.chuang-yen.org:80
.chubold.com:80
.chushigangdrug.ch:80
.cienen.com:80
.cineastentreff.de:80
.cipfg.org:80
.circlethebayfortibet.org
.cirosantilli.com
.citizencn.com
.citizenlab.org:80
.citizenscommission.hk
.city365.ca:80
.citypopulation.de
.civicparty.hk
.civildisobediencemovement.org:80
.civilhrfront.org
.civiliangunner.com:80
.civilmedia.tw
.ck101.com
.classicalguitarblog.net
.clb.org.hk:80
.cldr.unicode.org
.cleansite.biz:80
.cleansite.info:80
.cleansite.us:80
.clearsurance.com
.clementine-player.org
.clipfish.de:80
.cloud.feedly.com
.cloud.mail.ru
.club1069.com
.clyp.it
.cmcn.org
.cms.gov
.cmule.com
.cmule.org
.cmx.im
.cn-proxy.com:80
.cn.sandscotaicentral.com:80
.cn.uptodown.com
.cn6.eu:80
.cna.com.tw
.cnabc.com:80
.cnbbnews.wordpress.com
.cnd.org
.cnex.org.cn:80
.cnineu.com:80
.cnpolitics.org
.cnproxy.com:80
.co.ng.mil
.coat.co.jp
.cobinhood.com
.cochina.co
.cochina.org
.codeshare.io
.codeskulptor.org
.coin2co.in
.coinbene.com
.coinegg.com
.coinex.com
.coingi.com
.coinrail.co.kr
.cointiger.com
.cointobe.com
.coinut.com
.collateralmurder.com
.collateralmurder.org
.com.google
.comefromchina.com
.comic-mega.me:80
.commentshk.com
.communistcrimes.org
.community.windy.com
.communitychoicecu.com
.compileheart.com
.compress.to:80
.connect.facebook.net
.conoha.jp
.contactmagazine.net:80
.contests.twilio.com
.convio.net:80
.coobay.com:80
.coolaler.com
.coolder.com
.coolloud.org.tw
.coolncute.com:80
.coolstuffinc.com
.cos-moe.com:80
.cosplayjav.pl:80
.costco.com
.cotweet.com
.counter.social
.coursehero.com
.cpj.org
.cq99.us:80
.crackle.com
.crazys.cc:80
.crazyshit.com:80
.crbug.com
.crchina.org
.creaders.net
.creadersnet.com:80
.creativelab5.com
.crisisresponse.google
.cristyli.com
.crocotube.com:80
.crossfire.co.kr
.crossthewall.net
.crossvpn.net
.crrev.com
.crucial.com
.csdparty.com
.css.pixnet.in
.csuchen.de
.csw.org.uk:80
.ct.org.tw
.ctao.org:80
.ctfriend.net:80
.ctitv.com.tw:80
.cuihua.org
.cuiweiping.net
.culture.tw
.cumlouder.com
.curvefish.com
.cusu.hk
.cutscenes.net:80
.cw.com.tw
.cyberghostvpn.com
.cynscribe.com
.d-fukyu.com:80
.d100.net
.d2bay.com:80
.d2pass.com
.d3rhr7kgmtrq1v.cloudfront.net
.dabr.co.uk
.dabr.me
.dabr.mobi
.dadazim.com
.dadi360.com:80
.dafabet.com:80
.dafoh.org:80
.daftporn.com:80
.dagelijksestandaard.nl:80
.daidostup.ru:80
.dailidaili.com
.dailymotion.com
.dailyview.tw
.dajiyuan.com:80
.dajiyuan.de
.dalailama-archives.org:80
.dalailama.mn:80
.dalailama.ru
.dalailamacenter.org:80
.dalailamafilm.com:80
.dalailamafoundation.org:80
.dalailamahindi.com:80
.dalailamainaustralia.org:80
.dalailamajapanese.com:80
.dalailamaprotesters.info:80
.dalailamaquotes.org:80
.dalailamatrust.org:80
.dalailamavisit.org.nz:80
.dalailamaworld.com
.dalianmeng.org
.daliulian.org
.danke4china.net
.danwei.org:80
.daozhongxing.org:80
.darktech.org:80
.darpa.mil
.dastrassi.org
.data-vocabulary.org
.data.flurry.com
.data.gov.tw
.david-kilgour.com:80
.dawangidc.com
.daxa.cn
.db.tt
.dcard.tw
.ddc.com.tw:80
.ddhw.info:80
.ddns.info:80
.ddns.me.uk:80
.ddns.mobi:80
.ddns.ms:80
.ddns.name:80
.ddns.net:80
.ddns.us:80
.de-sci.org
.deaftone.com:80
.debug.com
.decodet.co
.deepmind.com
.deezer.com
.definebabe.com:80
.deja.com
.delcamp.net
.demo.opera-mini.net
.democrats.org
.depositphotos.com
.derekhsu.homeip.net
.desc.se
.design.google
.desipro.de
.dessci.com
.destroy-china.jp:80
.deutsche-welle.de
.developers.box.net
.devio.us
.devpn.com
.dfas.mil
.dharamsalanet.com:80
.dhcp.biz:80
.diaoyuislands.org
.dictionary.goo.ne.jp
.difangwenge.org:80
.digisfera.com
.digitalnomadsproject.org
.diigo.com
.dilber.se
.dingchin.com.tw
.dipity.com:80
.directcreative.com
.discoins.com
.discordapp.com
.discordapp.net
.discuss.com.hk
.discuss4u.com:80
.dish.com
.disqus.com
.dit-inc.us
.dizhidizhi.com:80
.dizhuzhishang.com
.djorz.com
.dl-laby.jp
.dl.box.net
.dlsite.com
.dlyoutube.com
.dm530.net
.dmcdn.net
.dmm.co.jp
.dns-dns.com:80
.dns-stuff.com:80
.dns04.com:80
.dns05.com:80
.dns1.us:80
.dns2.us:80
.dns2go.com
.dnscrypt.org
.dnset.com:80
.dnsrd.com:80
.dnssec.net
.dnvod.tv
.dojin.com:80
.dok-forum.net:80
.dolc.de
.dolf.org.hk
.dollf.com
.domain.club.tw:80
.domains.google
.domaintoday.com.au:80
.dongtaiwang.com
.dongtaiwang.net
.dongyangjing.com:80
.dontfilter.us:80
.dontmovetochina.com
.dorjeshugden.com:80
.dotplane.com
.dotsub.com
.dotvpn.com
.doub.io
.doubibackup.com
.doubmirror.cf
.dougscripts.com
.douhokanko.net
.doujincafe.com
.dpp.org.tw
.dpr.info
.dragonex.io
.dragonsprings.org
.dreamamateurs.com:80
.drepung.org:80
.drgan.net
.drmingxia.org:80
.dropbooks.tv
.dropbox.com
.dropboxusercontent.com
.drtuber.com:80
.dscn.info:80
.dsmtp.com:80
.dstk.dk:80
.dtdns.net:80
.dtiblog.com
.dtic.mil
.dtwang.org:80
.duanzhihu.com:80
.duck.com
.duckdns.org:80
.duckduckgo-owned-server.yahoo.net
.duckduckgo.com
.duckmylife.com
.duga.jp:80
.duihua.org
.duihuahrjournal.org
.dumb1.com:80
.dunyabulteni.net:80
.duoweitimes.com
.duplicati.com
.dushi.ca:80
.dvdpac.com
.dvorak.org
.dw-world.com
.dw-world.de:80
.dw.com
.dw.de
.dwnews.com
.dwnews.net
.dynamic-dns.net:80
.dynamicdns.biz:80
.dynamicdns.co.uk:80
.dynamicdns.me.uk:80
.dynamicdns.org.uk:80
.dynawebinc.com
.dyndns-ip.com:80
.dyndns-pics.com:80
.dyndns.org:80
.dyndns.pro:80
.dynssl.com:80
.dynu.com:80
.dynu.net:80
.dysfz.cc
.dzze.com:80
.e-classical.com.tw
.e-gold.com
.e-hentai.org
.e-hentaidb.com:80
.e123.hk
.earlytibet.com:80
.earthcam.com:80
.earthvpn.com
.easternlightning.org:80
.eastturkestan.com:80
.eastturkistan-gov.org:80
.eastturkistancc.org:80
.eastturkistangovernmentinexile.us
.easyca.ca:80
.easypic.com:80
.ebony-beauty.com:80
.ebook.hyread.com.tw
.ebtcbank.com
.ecfa.org.tw
.ecimg.tw
.economist.com:80
.edgecastcdn.net
.edmontonchina.cn:80
.edmontonservice.com:80
.edns.biz:80
.edubridge.com
.edupro.org:80
.eesti.ee
.eevpn.com
.effers.com:80
.efksoft.com
.efukt.com:80
.eic-av.com
.eireinikotaerukai.com
.eisbb.com:80
.eksisozluk.com
.elgoog.im
.ellawine.org:80
.elpais.com
.eltondisney.com:80
.embr.in
.empfil.com:80
.emule-ed2k.com:80
.emulefans.com:80
.emuparadise.me:80
.enanyang.my:80
.enewstree.com
.enfal.de:80
.engagedaily.org
.englishfromengland.co.uk
.enlighten.org.tw:80
.entermap.com
.entnt.com:80
.environment.google
.epa.gov.tw
.epac.to:80
.episcopalchurch.org:80
.epochhk.com:80
.epochtimes-bg.com
.epochtimes-romania.com
.epochtimes.co.il
.epochtimes.co.kr
.epochtimes.com
.epochtimes.cz:80
.epochtimes.ie:80
.epochtimes.it:80
.epochweek.com
.epochweekly.com
.eporner.com:80
.equinenow.com:80
.eracom.com.tw:80
.eraysoft.com.tr:80
.erepublik.com:80
.erights.net
.eriversoft.com
.erktv.com:80
.ernestmandel.org
.erodaizensyu.com
.erodoujinlog.com
.erodoujinworld.com
.eromanga-kingdom.com
.eromangadouzin.com
.eromon.net:80
.eroprofile.com:80
.eroticsaloon.net:80
.eslite.com
.esmtp.biz:80
.esurance.com
.etaa.org.au:80
.etadult.com:80
.etherdelta.com
.etizer.org
.etokki.com
.etools.ncol.com
.etowns.net:80
.etowns.org:80
.eu.org
.eucasino.com:80
.eulam.com:80
.eurekavpt.com
.euronews.com
.evschool.net:80
.exblog.jp
.exchristian.hk
.exmo.com
.exmormon.org
.expatshield.com
.expecthim.com
.expekt.com
.exploader.net
.expressvpn.com
.exrates.me
.extmatrix.com
.extremetube.com:80
.exx.com
.eyevio.jp
.eyny.com
.ezpeer.com:80
.ezua.com:80
.fa.gov.tw
.facebook.br
.facebook.com
.facebook.design
.facebook.hu
.facebook.in
.facebook.nl
.facebook.se
.facebookmail.com
.facebookquotes4u.com
.faceless.me
.facesofnyfw.com
.faith100.org:80
.faithfuleye.com:80
.faiththedog.info
.fakku.net
.falsefire.com
.falunasia.info
.falunaz.net:80
.falundafa-florida.org
.falundafa-nc.org
.falundafa-pa.net
.falundafa-sacramento.org
.falundafaindia.org
.falungong.club:80
.falungong.de:80
.falunhr.org
.falunpilipinas.net:80
.falunworld.net
.famunion.com
.fan-qiang.com:80
.fangbinxing.com
.fangeming.com:80
.fangeqiang.com
.fanglizhi.info
.fangmincn.org
.fangong.org
.fanhaodang.com:80
.fanqiang.tk:80
.fanqianghou.com
.fanqiangzhe.com
.fanswong.com
.fanyue.info:80
.faqserv.com:80
.fartit.com:80
.farwestchina.com:80
.fast.wistia.com
.fastpic.ru
.fastssh.com
.faststone.org
.fatbtc.com
.favstar.fm
.fawanghuihui.org:80
.fb.com
.fb.me
.fbaddins.com
.fbcdn.net
.fbsbx.com
.fbworkmail.com
.fc2.com:80
.fc2china.com:80
.fc2cn.com
.fda.gov.tw
.fdc64.de:80
.fdc64.org:80
.fdc89.jp:80
.feedburner.com
.feelssh.com
.feifeiss.com:80
.feitian-california.org:80
.feministteacher.com
.fengzhenghu.com
.fengzhenghu.net
.fevernet.com:80
.ffvpn.com:80
.fgmtv.org:80
.fhreports.net:80
.figprayer.com
.fileflyer.com
.files2me.com:80
.filesor.com
.filthdump.com:80
.financetwitter.com
.finchvpn.com
.findyoutube.com
.findyoutube.net
.fingerdaily.com:80
.firearmsworld.net:80
.firebaseio.com
.fireofliberty.org
.firetweet.io
.firstfivefollowers.com
.flagsonline.it:80
.flecheinthepeche.fr
.fleursdeslettres.com:80
.flgg.us
.flgjustice.org
.flickr.com
.flickriver.com:80
.fling.com:80
.flipboard.com
.flipkart.com
.flitto.com
.flnet.org:80
.flog.tw
.flyvpn.com
.flyzy2005.com
.fnac.be
.fnac.com
.fochk.org:80
.focustaiwan.tw
.focusvpn.com:80
.fofg-europe.net:80
.fofg.org
.fooooo.com
.foreignpolicy.com
.forum4hk.com:80
.fotile.me:80
.fourface.nodesnoop.com
.fourthinternational.org
.foxdie.us
.foxsub.com
.fpmt-osel.org:80
.fpmt.org:80
.fpmt.tw:80
.fpmtmexico.org
.fqrouter.com
.franklc.com
.freakshare.com:80
.free-hada-now.org:80
.free-ss.site
.free-ssh.com
.free4u.com.ar
.freealim.com
.freebrowser.org
.freechal.com:80
.freechina.news:80
.freechinaforum.org
.freechinaweibo.com
.freeddns.com:80
.freeddns.org:80
.freedomchina.info
.freedomhouse.org
.freedominfonetweb.wordpress.com
.freedomsherald.org
.freeforums.org:80
.freefq.com:80
.freefuckvids.com:80
.freegao.com
.freekwonpyong.org:80
.freelotto.com
.freenetproject.org
.freeopenvpn.com:80
.freeoz.org
.freessh.us
.freetcp.com:80
.freetibet.net:80
.freetibet.org
.freetibetanheroes.org:80
.freeviewmovies.com:80
.freevpn.me:80
.freewallpaper4.me
.freewebs.com:80
.freewechat.com
.freeweibo.com
.freewww.biz:80
.freewww.info:80
.freexinwen.com:80
.freeyoutubeproxy.net
.friendsoftibet.org:80
.fring.com
.fringenetwork.com
.from-pr.com:80
.from-sd.com:80
.fromchinatousa.net:80
.frommel.net
.frontlinedefenders.org:80
.frootvpn.com
.fscked.org
.fsurf.com:80
.ftp1.biz:80
.ftpserver.biz:80
.ftv.com.tw:80
.fuckcnnic.net
.fullerconsideration.com
.funf.tw:80
.funkyimg.com
.fuq.com:80
.furbo.org
.furhhdl.org:80
.furinkan.com
.furl.net
.futurechinaforum.org:80
.futuremessage.org
.fux.com:80
.fuyin.net:80
.fuyindiantai.org:80
.fuyu.org.tw:80
.fw.cm
.fxcm-chinese.com
.fxnetworks.com
.g-area.org
.g-queen.com
.g.co
.g0v.social
.g6hentai.com:80
.gabocorp.com
.gaeproxy.com:80
.gaforum.org:80
.galaxymacau.com:80
.galenwu.com
.galstars.net:80
.game735.com
.gamer-cds.cdn.hinet.net
.gamer.com.tw
.gamer2-cds.cdn.hinet.net
.gamez.com.tw
.gamousa.com:80
.gaoming.net
.gaopi.net:80
.gaozhisheng.net:80
.gaozhisheng.org:80
.gardennetworks.org
.gartlive.com
.gate-project.com
.gate.io
.gatecoin.com
.gather.com
.gatherproxy.com:80
.gaybubble.com:80
.gaycn.net:80
.gayhub.com:80
.gaymap.cc
.gaymenring.com:80
.gaytube.com:80
.gaywatch.com:80
.gazotube.com
.gcc.org.hk
.gclooney.com
.gcmasia.com
.gcpnews.com:80
.gcr.io
.geek-art.net
.geekheart.info
.gekikame.com:80
.gelbooru.com:80
.geocities.co.jp:80
.gerefoundation.org:80
.get.app
.get.how
.get.page
.getastrill.com
.getchu.com:80
.getcloak.com
.getfoxyproxy.org
.getfreedur.com:80
.getgom.com
.geti2p.net
.getlantern.org
.getmdl.io
.getoutline.org
.getsocialscope.com:80
.getsync.com
.gettrials.com:80
.gettyimages.com
.getuploader.com
.gfgold.com.hk:80
.gfsale.com
.gfw.press
.ggpht.com
.ggssl.com
.ghostpath.com
.ghut.org
.giantessnight.com:80
.gifree.com:80
.giga-web.jp
.girlbanker.com
.git.io
.gizlen.net
.gjczz.com
.glass8.eu
.global.bing.com
.globalrescue.net
.globaltm.org:80
.globalvoices.org
.globalvoicesonline.org
.globalvpn.net
.glock.com:80
.glorystar.me
.glype.com
.gmail.com
.gmhz.org
.gmll.org:80
.gmodules.com
.gmozomg.izihost.org
.gnci.org.hk
.go.nesnode.com
.go141.com
.goagent.biz
.goagentplus.com
.godfootsteps.org
.godoc.org
.godsdirectcontact.org:80
.godsimmediatecontact.com:80
.gogotunnel.com:80
.gohappy.com.tw
.gokbayrak.com:80
.golang.org
.goldbet.com:80
.goldbetsports.com
.goldeneyevault.com
.goldenfrog.com
.goldjizz.com:80
.goldstep.net:80
.goldwave.com
.gongwt.com:80
.goo.gl
.gooday.xyz:80
.gooddns.info:80
.goodreaders.com
.goodreads.com
.goodtv.com.tw:80
.goodtv.tv:80
.goofind.com
.google.ac
.google.ad
.google.ae
.google.af
.google.al
.google.am
.google.as
.google.at
.google.az
.google.ba
.google.be
.google.bf
.google.bg
.google.bi
.google.bj
.google.bs
.google.bt
.google.by
.google.ca
.google.cat
.google.cd
.google.cf
.google.cg
.google.ch
.google.ci
.google.cl
.google.cm
.google.co.ao
.google.co.bw
.google.co.ck
.google.co.cr
.google.co.id
.google.co.il
.google.co.in
.google.co.jp
.google.co.ke
.google.co.kr
.google.co.ls
.google.co.ma
.google.co.mz
.google.co.nz
.google.co.th
.google.co.tz
.google.co.ug
.google.co.uk
.google.co.uz
.google.co.ve
.google.co.vi
.google.co.za
.google.co.zm
.google.co.zw
.google.com
.google.com.af
.google.com.ag
.google.com.ai
.google.com.ar
.google.com.au
.google.com.bd
.google.com.bh
.google.com.bn
.google.com.bo
.google.com.br
.google.com.bz
.google.com.co
.google.com.cu
.google.com.cy
.google.com.do
.google.com.ec
.google.com.eg
.google.com.et
.google.com.fj
.google.com.gh
.google.com.gi
.google.com.gt
.google.com.hk
.google.com.jm
.google.com.kh
.google.com.kw
.google.com.lb
.google.com.ly
.google.com.mm
.google.com.mt
.google.com.mx
.google.com.my
.google.com.na
.google.com.nf
.google.com.ng
.google.com.ni
.google.com.np
.google.com.om
.google.com.pa
.google.com.pe
.google.com.pg
.google.com.ph
.google.com.pk
.google.com.pr
.google.com.py
.google.com.qa
.google.com.sa
.google.com.sb
.google.com.sg
.google.com.sl
.google.com.sv
.google.com.tj
.google.com.tr
.google.com.tw
.google.com.ua
.google.com.uy
.google.com.vc
.google.com.vn
.google.cv
.google.cz
.google.de
.google.dj
.google.dk
.google.dm
.google.dz
.google.ee
.google.es
.google.eu
.google.fi
.google.fm
.google.fr
.google.ga
.google.ge
.google.gg
.google.gl
.google.gm
.google.gp
.google.gr
.google.gy
.google.hk
.google.hn
.google.hr
.google.ht
.google.hu
.google.ie
.google.im
.google.iq
.google.is
.google.it
.google.it.ao
.google.je
.google.jo
.google.kg
.google.ki
.google.kz
.google.la
.google.li
.google.lk
.google.lt
.google.lu
.google.lv
.google.md
.google.me
.google.mg
.google.mk
.google.ml
.google.mn
.google.ms
.google.mu
.google.mv
.google.mw
.google.mx
.google.ne
.google.nl
.google.no
.google.nr
.google.nu
.google.org
.google.pl
.google.pn
.google.ps
.google.pt
.google.ro
.google.rs
.google.ru
.google.rw
.google.sc
.google.se
.google.sh
.google.si
.google.sk
.google.sm
.google.sn
.google.so
.google.sr
.google.st
.google.td
.google.tg
.google.tk
.google.tl
.google.tm
.google.tn
.google.to
.google.tt
.google.us
.google.vg
.google.vn
.google.vu
.google.ws
.googleapis.cn
.googleapis.com
.googleapps.com
.googlearth.com
.googleartproject.com
.googleblog.com
.googlebot.com
.googlechinawebmaster.com
.googlecode.com
.googlecommerce.com
.googledomains.com
.googledrive.com
.googleearth.com
.googlegroups.com
.googlehosted.com
.googleideas.com
.googleinsidesearch.com
.googlelabs.com
.googlemail.com
.googlemashups.com
.googlepagecreator.com
.googleplay.com
.googleplus.com
.googlescholar.com
.googlesile.com:80
.googlesource.com
.googleusercontent.com
.googlevideo.com
.googleweblight.com
.googlezip.net
.gopetition.com
.goproxing.net:80
.goregrish.com
.gospelherald.com
.got-game.org:80
.gotdns.ch
.gotgeeks.com:80
.gotrusted.com
.gotw.ca
.gov.taipei
.gov.tw:80
.gr8domain.biz:80
.gr8name.biz:80
.grammaly.com
.grangorz.org
.graphis.ne.jp
.graphql.org
.greasespot.net
.greatfire.org
.greatfire.us7.list-manage.com
.greatfirewallofchina.net
.greatfirewallofchina.org
.greatroc.tw
.greenfieldbookstore.com.hk
.greenparty.org.tw:80
.greenpeace.com.tw:80
.greenpeace.org
.greenvpn.net
.greenvpn.org:80
.grotty-monday.com
.groups.google.cn
.grow.google
.gsp.target.com
.gstatic.com
.gtricks.com
.gts-vpn.com:80
.gu-chu-sum.org:80
.guaguass.com:80
.guaguass.org:80
.guangming.com.my:80
.guardster.com:80
.guishan.org
.gumroad.com
.gun-world.net:80
.gunsamerica.com
.guo.media
.gutteruncensored.com
.gvm.com.tw
.gvt0.com
.gvt1.com
.gvt3.com
.gwtproject.org
.gyalwarinpoche.com:80
.gyatsostudio.com:80
.gzm.tv:80
.gzone-anime.info
.h-china.org
.h-moe.com:80
.h528.com:80
.h5dm.com:80
.h5galgame.me:80
.hacg.club
.hacg.in:80
.hacg.li:80
.hacg.me:80
.hacg.red:80
.hacker.org:80
.hackthatphone.net
.hakkatv.org.tw
.handcraftedsoftware.org:80
.hanunyi.com:80
.haoel.github.io
.happy-vpn.com
.haproxy.org:80
.hardsextube.com
.harunyahya.com:80
.hautelook.com
.hautelookcdn.com
.hbg.com
.hbo.com
.hclips.com:80
.hdlt.me
.hdtvb.net
.hdzog.com:80
.heartyit.com
.heavy-r.com:80
.hec.su:80
.hecaitou.net
.hechaji.com
.heeact.edu.tw
.hegre-art.com:80
.helloandroid.com
.helloqueer.com
.helloss.pw:80
.hellotxt.com
.help.linksalpha.com
.helpeachpeople.com
.helplinfen.com
.helpster.de
.helpzhuling.org:80
.hentai.to:80
.hentaivideoworld.com:80
.heungkongdiscuss.com
.hexieshe.com
.hexieshe.xyz
.hexxeh.net
.heyzo.com:80
.hgseav.com:80
.hhdcb3office.org:80
.hhthesakyatrizin.org:80
.hidden-advent.org
.hide.me
.hidein.net:80
.hideipvpn.com
.hideman.net
.hidemy.name
.hidemyass.com
.hidemycomp.com
.higfw.com:80
.highrockmedia.com
.hihiforum.com:80
.hihistory.net
.hiitch.com
.hikinggfw.org
.hilive.tv:80
.himalayan-foundation.org:80
.himemix.com
.himemix.net:80
.hitbtc.com
.hitomi.la:80
.hiwifi.com:80
.hjclub.info:80
.hk.jiepang.com
.hk.news.yahoo.com
.hk01.com
.hk32168.com
.hka8964.wordpress.com
.hkacg.com
.hkacg.net
.hkanews.wordpress.com
.hkatvnews.com:80
.hkbf.org:80
.hkbookcity.com
.hkchurch.org:80
.hkcmi.edu:80
.hkcnews.com
.hkcoc.com
.hkej.com:80
.hkfaa.com
.hkgalden.com
.hkgolden.com
.hkip.org.uk
.hkjp.org:80
.hklft.com:80
.hklts.org.hk
.hkreporter.com
.hkusu.net
.hkvwet.com:80
.hkwcc.org.hk:80
.hkzone.org
.hmonghot.com:80
.hmv.co.jp:80
.hmvdigital.ca
.hmvdigital.com
.hnjhj.com
.hnntube.com:80
.hola.com
.hola.org
.holyspiritspeaks.org
.homedepot.com
.homeperversion.com:80
.hongkongfp.com
.hongzhi.li
.hootsuite.com
.hoovers.com
.hopedialogue.org:80
.hopto.org:80
.hornygamer.com:80
.hornytrip.com:80
.hotav.tv:80
.hotels.cn:80
.hotpornshow.com:80
.hotshame.com:80
.hotspotshield.com
.hotvpn.com
.hougaige.com
.howtoforge.com
.hoxx.com
.hpa.gov.tw
.hqcdp.org
.hqjapanesesex.com
.hqsbnet.wordpress.com
.hqsbonline.wordpress.com
.hrcchina.org:80
.hrcir.com:80
.hrea.org:80
.hrichina.org
.hrtsea.com:80
.hrw.org
.hsjp.net
.hsselite.com
.hstern.net:80
.hstt.net:80
.htkou.net
.html5rocks.com
.https443.net:80
.https443.org:80
.hua-yue.net:80
.huaglad.com
.huanghuagang.org
.huangyiyu.com:80
.huaren.us
.huaren4us.com:80
.huashangnews.com:80
.huayuworld.org
.hudatoriq.web.id
.hudson.org
.hugoroy.eu
.huhaitai.com
.huhamhire.com
.hulkshare.com:80
.hulu.com
.huluim.com
.hung-ya.com
.hungerstrikeforaids.org
.huobi.com
.huobi.pro
.huobipro.com
.huping.net
.hurriyet.com.tr:80
.hut2.ru:80
.hutianyi.net
.hwadzan.tw:80
.hwayue.org.tw
.hwinfo.com
.hxwk.org
.hybrid-analysis.com
.hyperrate.com
.i-cable.com:80
.i-part.com.tw:80
.i.lithium.com
.i1.hk
.i2p2.de
.i2runner.com
.i818hk.com
.iam.soy
.iamtopone.com:80
.iask.bz
.iask.ca
.iav19.com:80
.iblist.com:80
.iblogserv-f.net
.ibvpn.com
.icij.org
.icl-fi.org
.icoco.com
.iconpaper.org
.icu-project.org
.id.heroku.com
.iddddg.com
.identi.ca
.idiomconnection.com
.idouga.com:80
.idreamx.com:80
.idv.tw:80
.ieasy5.com:80
.ied2k.net:80
.ienergy1.com:80
.ifan.cz.cc
.ifcss.org
.ifreewares.com
.ift.tt:80
.igcd.net
.igfw.net
.igfw.tech
.igmg.de:80
.ignitedetroit.net
.igoogle.com
.igotmail.com.tw:80
.igvita.com
.ihakka.net
.iicns.com
.ikstar.com:80
.ikwb.com:80
.illusionfactory.com
.ilove80.be
.ilovelongtoes.com
.im.tv
.im88.tw
.imageab.com:80
.imagefap.com
.imageflea.com
.images-gaytube.com
.images.comico.tw
.imagevenue.com
.imagezilla.net
.imb.org:80
.img*.picturedip.com
.img.ly
.imgchili.net:80
.imkev.com
.imlive.com
.immigration.gov.tw
.immoral.jp:80
.incapdns.net:80
.incloak.com
.incredibox.fr
.indiandefensenews.in
.indiemerch.com
.initiativesforchina.org:80
.inkui.com:80
.inmediahk.net
.innermongolia.org
.inote.tw:80
.insecam.org:80
.insidevoa.com
.instagram.com
.instanthq.com:80
.institut-tibetain.org:80
.international-news.newsmagazine.asia
.internetpopculture.com
.inthenameofconfuciusmovie.com
.investigating.wordpress.com
.inxian.com
.iownyour.biz:80
.iownyour.org:80
.ipfire.org:80
.ipfs.io
.iphone4hongkong.com
.iphonehacks.com
.iphonetaiwan.org
.iphonix.fr
.ipicture.ru
.ipjetable.net
.iportal.me:80
.ippotv.com
.ipredator.se
.iptv.com.tw:80
.iptvbin.com
.ipvanish.com
.ironbigfools.compython.net
.ironpython.net
.ironsocket.com
.is-a-hunter.com:80
.is.gd:80
.isaacmao.com
.isasecret.com:80
.isc.sans.edu
.isgreat.org
.islahhaber.net:80
.islam.org.hk:80
.islamhouse.com
.islamicity.com:80
.islamicpluralism.org:80
.islamtoday.net:80
.ismaelan.com
.ismalltits.com:80
.ismprofessional.net
.israbox.com
.issuu.com
.istars.co.nz:80
.istiqlalhewer.com:80
.istockphoto.com:80
.itaboo.info
.itaiwan.gov.tw
.italiatibet.org:80
.itasoftware.com
.itemdb.com:80
.itsaol.com:80
.itshidden.com
.itsky.it:80
.itweet.net:80
.iu45.com:80
.iuhrdf.org
.iuksky.com:80
.ivacy.com
.iverycd.com:80
.ivpn.net:80
.ixquick.com
.ixxx.com:80
.iyouport.com
.izaobao.us:80
.izles.net:80
.izlesem.org:80
.j.mp
.ja.wikipedia.org
.jamyangnorbu.com:80
.jandyx.com:80
.janwongphoto.com
.japan-whores.com
.japantimes.co.jp
.jav.com:80
.jav101.com:80
.jav2be.com
.jav68.tv:80
.javakiba.org:80
.javbus.com
.javfor.me
.javhd.com:80
.javhip.com:80
.javhub.net
.javhuge.com
.javlibrary.com
.javmobile.net:80
.javmoo.com:80
.javmoo.xyz:80
.javseen.com:80
.javtag.com:80
.javzoo.com:80
.jcpenney.com
.jdwsy.com:80
.jetos.com:80
.jex.com
.jfqu36.club
.jfqu37.xyz
.jgoodies.com
.jiangweiping.com
.jiaoyou8.com
.jiehua.cz:80
.jigglegifs.com:80
.jihadology.net:80
.jiji.com
.jims.net
.jinbushe.org
.jingpin.org
.jingsim.org:80
.jinroukong.com:80
.jintian.net
.jinx.com
.jitouch.com
.jizzthis.com:80
.jkb.cc:80
.jkub.com:80
.jma.go.jp
.jmscult.com:80
.joachims.org
.jobnewera.wordpress.com
.jobso.tv
.joinmastodon.org
.journalchretien.net:80
.journalofdemocracy.org
.joymiihub.com:80
.joyourself.com:80
.jpl.nasa.gov
.jtvnw.net
.jubushoushen.com
.juhuaren.com:80
.jukujo-club.com
.juliepost.com
.juliereyc.com
.junauza.com
.june4commemoration.org:80
.junefourth-20.net
.jungleheart.com:80
.juoaa.com:80
.justdied.com:80
.justicefortenzin.org:80
.juziyue.com
.jwmusic.org
.jyxf.net:80
.k-doujin.net
.ka-wai.com
.kagyu.org.za
.kagyu.org:80
.kagyumonlam.org:80
.kagyunews.com.hk:80
.kagyuoffice.org
.kagyuoffice.org.tw
.kaiyuan.de:80
.kakao.com
.kalachakralugano.org:80
.kankan.today:80
.kannewyork.com
.kanshifang.com
.kantie.org
.kaotic.com:80
.karayou.com
.karmapa-teachings.org:80
.karmapa.org:80
.kawaiikawaii.jp
.kawase.com
.kb.monitorware.com
.kba-tx.org:80
.kcoolonline.com:80
.kebrum.com
.kechara.com:80
.keezmovies.com:80
.kendatire.com
.kendincos.net:80
.kenengba.com
.keontech.net
.kepard.com
.kex.com
.keycdn.com
.khabdha.org:80
.khatrimaza.org
.khmusic.com.tw:80
.kichiku-doujinko.com
.kik.com
.killwall.com
.kindleren.com:80
.kingdomsalvation.org
.kingstone.com.tw
.kink.com:80
.kinmen.org.tw
.kinmen.travel
.kir.jp:80
.kissbbao.cn:80
.kk-whys.co.jp
.kkbox.com
.kknews.cc
.kmuh.org.tw:80
.kobo.com
.kobobooks.com
.kodingen.com
.kompozer.net
.konachan.com:80
.kone.com:80
.koolsolutions.com
.koornk.com
.koranmandarin.com
.korenan2.com:80
.ksdl.org:80
.ksnews.com.tw:80
.kspcoin.com
.ktzhk.com
.kucoin.com
.kurashsultan.com:80
.kurtmunger.com
.kwcg.ca
.kxsw.life
.kyofun.com:80
.kyoyue.com
.kyzyhello.com
.kzeng.info
.labiennale.org
.lagranepoca.com
.lalulalu.com:80
.lama.com.tw
.lamayeshe.com:80
.lamnia.co.uk
.lanterncn.cn:80
.lantosfoundation.org:80
.laod.cn:80
.laogai.org
.laoyang.info:80
.laptoplockdown.com
.laqingdan.net
.larsgeorge.com
.lastcombat.com:80
.lastfm.es
.latibet.org:80
.lbank.info
.le-vpn.com
.leafyvpn.net
.lecloud.net
.left21.hk
.legalporno.com:80
.legaltech.law.com
.legsjapan.com:80
.leisurepro.com
.lematin.ch
.lemonde.fr:80
.lenwhite.com
.lerosua.org
.lers.google
.lesoir.be
.letou.com:80
.letscorp.net
.lflink.com:80
.lflinkup.com:80
.lflinkup.net:80
.lflinkup.org:80
.lhakar.org:80
.lhasocialwork.org:80
.liangyou.net
.liangzhichuanmei.com
.lianyue.net:80
.liaowangxizang.net
.liberal.org.hk
.libertytimes.com.tw:80
.lifemiles.com
.lighten.org.tw:80
.lightnovel.cn:80
.lihkg.com
.like.com
.line-apps.com
.line-scdn.net
.line.me
.line.naver.jp
.linear-abematv.akamaized.net
.linglingfa.com:80
.lingvodics.com
.link-o-rama.com:80
.linkideo.com:80
.linux.org.hk
.lionsroar.com:80
.lipuman.com:80
.liquidvpn.com
.listentoyoutube.com
.liu-xiaobo.org:80
.liudejun.com
.liuhanyu.com:80
.liujianshu.com
.liuxiaobo.net:80
.liuxiaotong.com
.livecoin.net
.livedoor.jp:80
.liveleak.com
.livestation.com:80
.livestream.com
.livevideo.com
.livingonline.us
.livingstream.com
.liwangyang.com:80
.llss.me:80
.load.to:80
.lobsangwangyal.com:80
.localbitcoins.com
.localdomain.ws
.lockestek.com
.login.target.com
.logiqx.com
.londonchinese.ca:80
.longhair.hk:80
.longmusic.com:80
.longtermly.net
.longtoes.com
.lookpic.com
.looktoronto.com:80
.lotuslight.org.hk:80
.lotuslight.org.tw:80
.lovetvshow.com
.lpsg.com
.lrfz.com
.lrip.org
.lsd.org.hk
.lsm.org
.lsmchinese.org
.lsmkorean.org
.lsmwebcast.com:80
.lsxszzg.com:80
.ltn.com.tw:80
.luke54.com:80
.luke54.org:80
.lupm.org
.lushstories.com
.lvhai.org
.lvv2.com
.lyfhk.net:80
.lzmtnews.org
.m-team.cc:80
.m.me
.m.plixi.com
.macgamestore.com
.macrovpn.com:80
.mad-ar.ch
.madewithcode.com
.madonna-av.com
.madrau.com
.madthumbs.com
.magazines.sina.com.tw
.magic-net.info
.maiio.net:80
.mail-archive.com:80
.maildns.xyz:80
.maiplus.com:80
.maizhong.org:80
.makemymood.com
.makzhou.warehouse333.com:80
.malaysiakini.com:80
.mamingzhe.com:80
.manchukuo.net:80
.mangafox.com
.mangafox.me
.maniash.com:80
.mansion.com:80
.mansionpoker.com:80
.manta.com
.maplew.com:80
.marc.info
.martau.com
.martincartoons.com
.martsangkagyuofficial.org:80
.marxist.com:80
.marxist.net
.mastodon.cloud
.mastodon.host
.mastodon.social
.matainja.com
.material.io
.mathable.io
.mathiew-badimon.com
.matome-plus.com
.matome-plus.net
.matsushimakaede.com
.matters.news
.mattwilcox.net
.maxing.jp:80
.mcadforums.com
.mcaf.ee:80
.md-t.org
.me.me
.meansys.com
.media.nu.nl
.media.org.hk:80
.mediachinese.com
.mediafreakcity.com
.medium.com
.meetav.com:80
.meetup.com
.mefound.com:80
.mega.nz
.megaproxy.com
.megarotic.com
.megurineluka.com
.meltoday.com:80
.memehk.com
.memri.org:80
.memrijttm.org:80
.mercatox.com
.mercyprophet.org:80
.mergersandinquisitions.org
.meridian-trust.org:80
.meripet.biz:80
.meripet.com:80
.messenger.com
.metart.com
.metarthunter.com
.meteorshowersonline.com
.metrolife.ca
.metroradio.com.hk:80
.meyul.com:80
.mfxmedia.com
.mgoon.com
.mgstage.com
.mh4u.org
.michaelmarketl.com
.microvpn.com:80
.mihr.com:80
.mike.cz.cc
.mikesoltys.com
.milph.net:80
.milsurps.com:80
.mimivip.com:80
.mimivv.com:80
.mindrolling.org:80
.minghui.or.kr:80
.minghui.org
.minghuiyw.wordpress.com
.mingjinglishi.com
.mingjingtimes.com
.mingpao.com
.mingpaocanada.com:80
.mingpaomonthly.com:80
.mingpaony.com:80
.mingpaosf.com:80
.mingpaotor.com:80
.mingpaovan.com:80
.mingshengbao.com:80
.minhhue.net:80
.miniforum.org:80
.ministrybooks.org:80
.minzhuhua.net
.miroguide.com
.mist.vip:80
.mitao.com.tw:80
.mitbbs.com
.mixero.com
.mixx.com
.mizzmona.com
.mjib.gov.tw
.mk5000.com:80
.mlcool.com:80
.mlzs.work
.mm-cg.com:80
.mmaaxx.com
.mmmca.com:80
.mobatek.net
.mobile01.com
.mobileways.de
.mobypicture.com:80
.moeaic.gov.tw
.moeerolibrary.com
.mofa.gov.tw
.mofaxiehui.com:80
.mofos.com:80
.mog.com
.mohu.club
.mohu.ml
.mojim.com
.mol.gov.tw
.mondex.org
.money-link.com.tw:80
.moneyhome.biz:80
.monitorchina.org
.monster.com
.moodyz.com
.moonbbs.com
.moonbingo.com
.morningsun.org
.moroneta.com
.mos.ru
.motherless.com:80
.motiyun.com
.mousebreaker.com:80
.movements.org
.moviefap.com
.mp3buscador.com:80
.mpettis.com
.mqxd.org:80
.mrbasic.com:80
.mrbonus.com:80
.mrface.com:80
.mrslove.com:80
.mrtweet.com
.msa-it.org
.msha.gov
.mswe1.org:80
.mthruf.com
.mtw.tl
.mullvad.net
.multiply.com
.mummysgold.com:80
.murmur.tw:80
.musicade.net:80
.muslimvideo.com:80
.muzi.com
.muzi.net
.muzu.tv
.mvdis.gov.tw
.mvg.jp
.mx981.com
.my-formosa.com:80
.my-private-network.co.uk
.my-proxy.com:80
.my.pcloud.com
.my03.com:80
.myanniu.com
.myaudiocast.com
.mybbs.us:80
.mybet.com
.myca168.com:80
.mycanadanow.com:80
.mychinamyhome.com
.mychinanet.com:80
.mychinanews.com
.mychinese.news:80
.mycnnews.com
.mydad.info:80
.myddns.com:80
.myeasytv.com:80
.myeclipseide.com
.myforum.com.hk
.myforum.com.uk
.myfreecams.com:80
.myfreepaysite.com:80
.myfreshnet.com:80
.myftp.info:80
.myftp.name:80
.myiphide.com
.mykomica.org
.mylftv.com:80
.mymoe.moe
.mymom.info:80
.mymusic.net.tw
.mynetav.net:80
.mynetav.org:80
.mynumber.org:80
.myparagliding.com
.mypicture.info:80
.mypop3.net:80
.mypop3.org:80
.mypopescu.com
.myreadingmanga.info:80
.mysecondarydns.com:80
.myspace.com:80
.myspacecdn.com
.mytalkbox.com:80
.mytizi.com:80
.mywww.biz:80
.myz.info:80
.naacoalition.org
.naitik.net
.nakido.com
.nalandabodhi.org
.nalandawest.org
.namgyal.org:80
.namsisi.com
.nanyang.com
.nanyangpost.com
.nanzao.com:80
.naol.ca:80
.naol.cc:80
.nat.gov.tw
.nat.moe
.national-lottery.co.uk
.nationwide.com
.naughtyamerica.com
.navyfamily.navy.mil
.navyreserve.navy.mil
.nbtvpn.com:80
.nch.com.tw:80
.ncn.org
.nde.de:80
.ndr.de:80
.ned.org:80
.nekoslovakia.net
.neo-miracle.com
.nepusoku.com
.net-fits.pro
.netbirds.com:80
.netflix.com
.netme.cc
.network54.com:80
.networktunnel.net:80
.new-akiba.com:80
.new96.ca:80
.newcenturymc.com:80
.newchen.com
.newgrounds.com:80
.newlandmagazine.com.au:80
.newnews.ca:80
.news.now.com:80
.newsancai.com
.newscn.org
.newsdetox.ca:80
.newsdh.com:80
.newstamago.com
.newstapa.org
.newtaiwan.com.tw:80
.newtalk.tw
.nexon.com
.next11.co.jp:80
.nextmag.com.tw:80
.nextmedia.com:80
.nexton-net.jp
.nf.id.au
.nfjtyd.com:80
.nflxext.com
.nflximg.com
.nflximg.net
.nflxso.net
.nflxvideo.net
.nga.mil
.nhentai.net:80
.nhi.gov.tw
.nhk-ondemand.jp:80
.nic.cz.cc
.nic.google
.nic.gov
.nighost.org
.nikkei.com
.ninjacloak.com:80
.ninjaproxy.ninja
.ninth.biz:80
.niu.moe
.niusnews.com
.njactb.org
.njuice.com
.nko.navy.mil
.no-ip.org:80
.nobel.se
.nobodycanstop.us
.nofile.io
.nokogiri.org
.nokola.com
.norbulingka.org:80
.nordstrom.com
.nordstromimage.com
.nordstromrack.com
.nordvpn.com
.notify.dropboxapi.com
.nottinghampost.com
.novelasia.com
.now.com
.now.im:80
.nownews.com
.nowtorrents.com:80
.noypf.com
.npa.go.jp
.npa.gov.tw
.npnt.me:80
.nps.gov:80
.npsboost.com
.nradio.me:80
.nrk.no
.ns01.biz:80
.ns01.info:80
.ns01.us:80
.ns02.biz:80
.ns02.info:80
.ns02.us:80
.ns1.name:80
.ns2.name:80
.ns3.name:80
.nsc.gov.tw
.ntbk.gov.tw
.ntbna.gov.tw
.ntbt.gov.tw
.ntd.tv
.ntdtv.co.kr:80
.ntdtv.com
.ntdtv.cz
.ntrfun.com:80
.ntsna.gov.tw
.nubiles.net:80
.nuexpo.com
.nukistream.com:80
.nurgo-software.com
.nusatrip.com
.nutaku.net
.nuuvem.com
.nuvid.com:80
.nvdst.com
.nvquan.org:80
.nvtongzhisheng.org:80
.nwtca.org:80
.nydus.ca:80
.nyt.com
.nytcn.me
.nytco.com
.nytimes.com
.nytimes.map.fastly.net
.nytimg.com
.nytstyle.com
.nzchinese.com:80
.nzchinese.net.nz
.obutu.com:80
.ocreampies.com:80
.ocry.com:80
.october-review.org
.oculus.com
.oculuscdn.com
.oex.com
.ogaoga.org
.ogate.org
.oiktv.com:80
.ok.ru
.okayfreedom.com
.okex.com
.olumpo.com
.olympicwatch.org:80
.omni7.jp
.omnitalk.com
.omnitalk.org
.on.cc
.on2.com
.onapp.com
.onedrive.live.com
.onedumb.com:80
.onejav.com
.onion
.onion.city
.onlinecha.com:80
.onlineyoutube.com
.onlytweets.com:80
.onmypc.biz:80
.onmypc.info:80
.onmypc.net:80
.onmypc.org:80
.onmypc.us:80
.onthehunt.com:80
.ontrac.com
.oopsforum.com:80
.opendemocracy.net
.opendn.xyz:80
.openervpn.in:80
.openid.net
.openleaks.org
.openvpn.net
.openvpn.org
.openwebster.com
.openwrt.org.cn:80
.opus-gaming.com:80
.organcare.org.tw:80
.organiccrap.com:80
.orgasm.com:80
.orgfree.com:80
.orient-doll.com
.orientaldaily.com.my
.orn.jp
.orzistic.org
.osfoora.com
.otcbtc.com
.otnd.org
.otto.de
.otzo.com:80
.ourdearamy.com
.ourhobby.com:80
.oursteps.com.au
.oursweb.net:80
.ourtv.hk
.overplay.net
.oversea.istarshine.com
.ow.ly
.ozvoice.org
.ozxw.com:80
.ozyoyo.com:80
.pachosting.com
.pacificpoker.com:80
.packetix.net:80
.pacopacomama.com
.padmanet.com:80
.pagodabox.com
.palacemoon.com:80
.paldengyal.com:80
.paltalk.com:80
.pandapow.co
.pandapow.net:80
.pandavpn-jp.com:80
.pandora.com
.pandora.tv:80
.panluan.net
.panoramio.com
.pao-pao.net
.paradisehill.cc:80
.paradisepoker.com:80
.parkansky.com
.partycasino.com:80
.partypoker.com:80
.passion.com
.passiontimes.hk:80
.paste.ee
.pastie.org
.pbworks.com
.pbxes.com
.pbxes.org
.pcanywhere.net:80
.pcc.gov.tw
.pchome.com.tw:80
.pcstore.com.tw:80
.pct.org.tw
.pdproxy.com
.pds.nasa.gov
.peace.ca
.peacehall.com
.peeasian.com:80
.pekingduck.org
.pemulihan.or.id:80
.pen.io
.penchinese.net
.penthouse.com:80
.peoplebookcafe.com:80
.peoplenews.tw
.peopo.org
.percy.in:80
.perfectgirls.net:80
.periscope.tv
.persecutionblog.com:80
.persiankitty.com:80
.phmsociety.org
.phncdn.com
.phosphation13.rssing.com
.photodharma.net
.photofocus.com
.phuquocservices.com
.picacomic.com
.picacomiccn.com
.picasaweb.com
.picidae.net:80
.pimg.tw:80
.pin-cong.com
.pin6.com
.pincong.rocks
.ping.fm
.pinimg.com
.pinkrod.com:80
.pinoy-n.com
.pinterest.at
.pinterest.co.kr
.pinterest.co.uk
.pinterest.com
.pinterest.de
.pinterest.dk
.pinterest.fr
.pinterest.jp
.pinterest.nl
.pinterest.se
.pipii.tv:80
.piposay.com:80
.piring.com:80
.pixelqi.com
.pixiv.net
.pixnet.net
.pk.com:80
.pki.goog
.placemix.com
.playboy.com
.playboyplus.com
.player.fm
.playno1.com
.playpcesor.com
.plurk.com
.plus28.com:80
.plusbb.com:80
.pmatehunter.com:80
.pmates.com:80
.po2b.com
.podictionary.com
.pokerstars.com
.pokerstars.net:80
.politiscales.net:80
.poloniex.com
.polymer-project.org
.polymerhk.com:80
.popo.tw:80
.popvote.hk
.popyard.com:80
.popyard.org
.porn.com:80
.porn2.com:80
.porn5.com:80
.pornbase.org:80
.pornerbros.com:80
.pornhd.com
.pornhost.com:80
.pornhub.com
.pornhubdeutsch.net:80
.pornmm.net
.pornoxo.com:80
.pornrapidshare.com
.pornsharing.com:80
.pornsocket.com:80
.pornstarclub.com
.porntube.com:80
.porntubenews.com:80
.porntvblog.com
.pornvisit.com:80
.port25.biz:80
.portablevpn.nl:80
.poskotanews.com
.post01.com:80
.post76.com
.post852.com:80
.postimg.org:80
.potvpn.com
.power.com
.powerapple.com
.powercx.com
.powerphoto.org:80
.prayforchina.net
.premeforwindows7.com
.premproxy.com
.presentationzen.com
.presidentlee.tw
.prestige-av.com
.pride.google
.prisoneralert.com:80
.pritunl.com
.privacybox.de
.privateinternetaccess.com
.privatepaste.com
.privatetunnel.com
.privatevpn.com
.procopytips.com
.prosiben.de
.protonvpn.com
.provpnaccounts.com
.proxfree.com
.proxomitron.info
.proxpn.com
.proxydns.com:80
.proxylist.org.uk
.proxynetwork.org.uk
.proxypy.net
.proxytunnel.net:80
.proyectoclubes.com
.psblog.name
.pscp.tv
.psiphon.ca
.psiphon3.com
.psiphontoday.com:80
.pts.org.tw
.ptt.cc
.pttvan.org:80
.puffstore.com:80
.pullfolio.com
.pure18.com
.pureconcepts.net
.pureinsight.org
.purepdf.com
.purevpn.com
.purplelotus.org:80
.pursuestar.com
.pushchinawall.com:80
.pussyspace.com:80
.putihome.org:80
.putty.org
.puuko.com:80
.python.com.tw:80
.pytorch.org
.qanote.com
.qgirl.com.tw:80
.qhigh.com:80
.qi-gong.me
.qiandao.today
.qiangyou.org
.qidian.ca:80
.qienkuen.org
.qiwen.lu
.qkshare.com:80
.qoos.com
.qpoe.com:80
.qq.co.za
.qstatus.com
.qtrac.eu
.qtweeter.com
.quannengshen.org:80
.questvisual.com
.quitccp.net
.quitccp.org
.quora.com
.quoracdn.net
.quran.com:80
.quranexplorer.com:80
.qvodzy.org:80
.r18.com
.ra.gg:80
.radicalparty.org:80
.radiohilight.net
.radiovaticana.org
.radiovncr.com
.rael.org
.raggedbanner.com
.raidcall.com.tw
.raidtalk.com.tw:80
.raizoji.or.jp:80
.ramcity.com.au
.ranyunfei.com
.rapbull.net:80
.rapidmoviez.com
.rapidvpn.com
.raremovie.cc:80
.raremovie.net:80
.rawgit.com
.rawgithub.com
.razyboard.com
.rcam.target.com
.rd.com
.rdio.com
.read01.com
.read100.com:80
.readingtimes.com.tw
.readmoo.com
.readydown.com:80
.realcourage.org:80
.realitykings.com
.realraptalk.com:80
.realsexpass.com:80
.rebatesrule.net:80
.recordhistory.org:80
.recovery.org.tw:80
.recoveryversion.com.tw
.red-lang.org
.redchinacn.net:80
.redd.it
.reddit.com
.redditlist.com:80
.redditmedia.com
.redditstatic.com
.redhotlabs.com
.referer.us
.reflectivecode.com
.registry.google
.relay.com.tw:80
.releaseinternational.org:80
.renminbao.com
.renyurenquan.org
.resilio.com
.retweeteffect.com
.retweetrank.com
.reuters.com
.reutersmedia.net
.revleft.com:80
.rfa.org
.rfachina.com:80
.rfamobile.org:80
.rferl.org
.rfi.fr
.rg3.github.io
.rightbtc.com
.rigpa.org:80
.rileyguide.com:80
.ritouki.jp:80
.ritter.vg
.rixcloud.com
.rixcloud.us
.rlwlw.com
.rmjdw.com:80
.rmjdw132.info:80
.roadshow.hk:80
.roboforex.com:80
.robustnessiskey.com
.rocket-inc.net
.rocksdb.org
.rojo.com
.rolia.net
.ronjoneswriter.com
.roodo.com:80
.rosechina.net:80
.rotten.com:80
.rsdlmonitor.com
.rsf-chinese.org
.rsf.org
.rsgamen.org:80
.rssmeme.com
.rtalabel.org
.rthk.hk:80
.rthk.org.hk:80
.rti.org.tw
.rtycminnesota.org:80
.runbtx.com:80
.rushbee.com:80
.ruten.com.tw:80
.ruyiseek.com:80
.rxhj.net:80
.s-cute.com
.s-dragon.org:80
.s1.nudezz.com
.s1heng.com
.s1s1s1.com:80
.s3-ap-southeast-2.amazonaws.com
.s3.amazonaws.com:443
.s8forum.com
.sacks.com
.sacom.hk
.sadistic-v.com
.sadpanda.us
.safervpn.com
.safety.google
.saintyculture.com:80
.saiq.me
.sakuralive.com
.sakya.org:80
.salvation.org.hk
.sambhota.org:80
.sanmin.com.tw:80
.saveliuxiaobo.com
.savethedate.foo
.savethesounds.info
.savetibet.de
.savetibet.org
.savetibetstore.org
.say2.info
.sbme.me:80
.scache.vzw.com
.scache1.vzw.com
.scache2.vzw.com
.scasino.com:80
.schema.org
.sciencenets.com:80
.scieron.com:80
.scmp.com
.scmpchinese.com:80
.scramble.io
.scribd.com
.scriptspot.com
.search.aol.com
.search.yahoo.co.jp
.search.yahoo.com
.searchtruth.com:80
.secretchina.com
.secretgarden.no
.secretsline.biz
.secure.logmein.com
.secure.raxcdn.com
.securetunnel.com
.securitykiss.com
.seed4.me
.seevpn.com
.seezone.net
.sellclassics.com:80
.sendsmtp.com:80
.sendspace.com:80
.servehttp.com:80
.serveuser.com:80
.serveusers.com:80
.sesawe.net
.sesawe.org:80
.sethwklein.net
.setn.com:80
.settv.com.tw:80
.sevenload.com
.sex-11.com:80
.sex.com:80
.sex3.com
.sex8.cc
.sexandsubmission.com:80
.sexbot.com:80
.sexhu.com:80
.sexhuang.com:80
.sexidude.com:80
.sexinsex.net
.sextvx.com:80
.sexxxy.biz:80
.sf.net:80
.sfileydy.com:80
.sfshibao.com
.sftindia.org:80
.sftuk.org
.shadeyouvpn.com
.shadowsky.xyz:80
.shadowsocks-r.com
.shadowsocks.asia:80
.shadowsocks.be
.shadowsocks.com.hk
.shadowsocks.com:80
.shadowsocks.org
.shadowsocks9.com
.shambalapost.com:80
.shambhalasun.com:80
.shangfang.org
.sharebee.com:80
.sharecool.org
.sharpdaily.com.hk
.sharpdaily.hk:80
.sharpdaily.tw:80
.shat-tibet.com:80
.shattered.io
.shellfire.de
.shenshou.org:80
.shenyunperformingarts.org
.shenzhoufilm.com
.sherabgyaltsen.com
.shiatv.net:80
.shicheng.org:80
.shiksha.com
.shireyishunjian.com:80
.shitaotv.org:80
.shixiao.org
.shizhao.org
.shodanhq.com
.shooshtime.com
.shop2000.com.tw:80
.shopping.com:80
.showhaotu.com:80
.showtime.jp:80
.shutterstock.com
.shwchurch.org:80
.shwchurch3.com:80
.siddharthasintent.org:80
.sidelinesnews.com
.sidelinessportseatery.com:80
.sierrafriendsoftibet.org:80
.sijihuisuo.club:80
.sijihuisuo.com:80
.sikaozhe1997.github.io
.silkbook.com:80
.simbolostwitter.com
.simplecd.org
.singaporepools.com.sg
.singfortibet.com:80
.singpao.com.hk:80
.singtao.com
.singtaousa.com
.sinoants.com
.sinocast.com
.sinonet.ca:80
.sinopitt.info:80
.sinoquebec.com:80
.sis001.com
.site2unblock.com:80
.site90.net
.sitebro.tw:80
.sitekreator.com
.siteks.uk.to
.sitemaps.org
.six-degrees.io
.sixth.biz:80
.sjrt.org:80
.sjum.cn
.sketchappsources.com
.skimtube.com
.skybet.com
.skyking.com.tw:80
.skyvegas.com
.skyxvpn.com
.slacker.com
.slaytizle.com:80
.sleazydream.com:80
.slheng.com
.slickvpn.com
.slideshare.net
.slinkset.com:80
.slutload.com:80
.slutmoonbeam.com
.slyip.com:80
.slyip.net:80
.sm-miracle.com
.smartdnsproxy.com
.smarthide.com:80
.smyxy.org:80
.snapchat.com
.snaptu.com
.sndcdn.com
.sobees.com
.soc.mil
.socks-proxy.net
.sockscap64.com:80
.sockslist.net
.socrec.org:80
.sod.co.jp:80
.sodatea.github.io
.softether-download.com
.softether.co.jp:80
.softether.org
.softsmirror.cf
.softwarebychuck.com
.sogclub.com
.sogrady.me
.soh.tw
.sohcradio.com
.sohfrance.org
.sokmil.com:80
.solarsystem.nasa.gov
.solidaritetibet.org:80
.solidfiles.com:80
.somee.com
.songjianjun.com
.sonicbbs.cc:80
.sonidodelaesperanza.org:80
.sopcast.com:80
.sopcast.org:80
.sorazone.net:80
.sorting-algorithms.com
.sos.org
.sosreader.com
.sostibet.org:80
.soubory.com:80
.soul-plus.net:80
.soulcaliburhentai.net
.soumo.info:80
.soundcloud.com
.soundofhope.kr:80
.soundofhope.org
.soup.io
.soupofmedia.com
.sourcewadio.com:80
.soylentnews.org
.spaces.hightail.com
.spankbang.com
.spankingtube.com:80
.spankwire.com:80
.spb.com
.speakerdeck.com
.speedify.com
.spencertipping.com
.spendee.com
.spicevpn.com
.spideroak.com
.spike.com:80
.sports.williamhill.com
.spotflux.com
.spotify.com
.spreadshirt.es
.spring4u.info:80
.springboardplatform.com
.sprite.org
.sproutcore.com
.sproxy.info
.squirly.info:80
.srocket.us
.ss-link.com
.ss.levyhsu.com
.ss7.vzw.com
.ssglobal.me:80
.ssh91.com
.ssl.webpack.de
.ssl443.org:80
.sspanel.net
.sspro.ml:80
.ssr.tools
.ssrshare.com
.sss.camp
.sstmlt.moe
.sstmlt.net
.stage64.hk
.standupfortibet.org
.starfishfx.com:80
.starp2p.com
.startpage.com
.startuplivingchina.com:80
.stat.gov.tw
.static-economist.com
.static.comico.tw
.static.shemalez.com
.staticflickr.com
.statueofdemocracy.org
.stc.com.sa
.steamcommunity.com
.steel-storm.com
.steganos.com
.steganos.net:80
.stepchina.com:80
.stephaniered.com
.sthoo.com
.stickam.com:80
.stileproject.com:80
.sto.cc:80
.stoporganharvesting.org:80
.stoptibetcrisis.net
.storagenewsletter.com
.stories.google
.storify.com
.storm.mg
.stormmediagroup.com:80
.stoweboyd.com
.straplessdildo.com
.streamingthe.net
.strikingly.com:80
.strongvpn.com
.strongwindpress.com:80
.studentsforafreetibet.org
.stumbleupon.com
.successfn.com:80
.sugarsync.com
.sugobbs.com:80
.sugumiru18.com
.suissl.com
.sujiatun.wordpress.com
.sukebei.nyaa.si
.sulian.me
.sumrando.com
.sunmedia.ca
.sunporno.com
.sunskyforum.com:80
.sunta.com.tw:80
.sunvpn.net:80
.sunwinism.joinbbs.net:80
.suoluo.org:80
.supchina.com
.superfreevpn.com:80
.superokayama.com
.superpages.com
.supervpn.net
.superzooi.com:80
.suppig.net:80
.suprememastertv.com:80
.surfeasy.com
.surfeasy.com.au:80
.suroot.com:80
.surrenderat20.net
.sustainability.google
.suyangg.com:80
.svsfx.com:80
.swagbucks.com
.swissinfo.ch
.swissvpn.net
.switch1.jp
.switchvpn.net
.sydneytoday.com
.sylfoundation.org:80
.syncback.com
.synergyse.com
.sytes.net:80
.szbbs.net:80
.szetowah.org.hk:80
.t-g.com
.t.co
.t.me
.t.orzdream.com
.t35.com:80
.t66y.com
.taa-usa.org:80
.taaze.tw
.tacc.cwb.gov.tw
.tacem.org:80
.taconet.com.tw:80
.taedp.org.tw
.tafm.org:80
.tagwa.org.au:80
.tagwalk.com
.taipei.gov.tw
.taipeisociety.org
.taiwanbible.com:80
.taiwancon.com:80
.taiwandaily.net
.taiwandc.org:80
.taiwanjobs.gov.tw
.taiwanjustice.com:80
.taiwanjustice.net
.taiwanncf.org.tw
.taiwannews.com.tw
.taiwantt.org.tw
.talk853.com:80
.talkboxapp.com
.talkcc.com
.talkonly.net
.tamiaode.tk
.tanc.org
.tangren.us:80
.taoism.net:80
.taolun.info
.tapanwap.com
.tapatalk.com
.tascn.com.au:80
.taup.net
.taweet.com
.tbcollege.org
.tbi.org.hk:80
.tbicn.org:80
.tbjyt.org:80
.tbpic.info
.tbrc.org:80
.tbsec.org
.tbsmalaysia.org:80
.tbsn.org
.tbsseattle.org:80
.tbssqh.org:80
.tbtemple.org.uk:80
.tbthouston.org:80
.tccwonline.org:80
.tcewf.org:80
.tcpspeed.co
.tcpspeed.com
.tcsofbc.org:80
.tcsovi.org:80
.tdm.com.mo:80
.teachparentstech.org
.techviz.net
.teck.in
.teco-hk.org
.teco-mo.org
.teddysun.com
.teeniefuck.net:80
.telecomspace.com:80
.telegram.dog
.telegram.me
.telegram.org
.telegramdownload.com:80
.telegraph.co.uk
.telesco.pe
.tellme.pw:80
.tenacy.com:80
.tensorflow.org
.tenzinpalmo.com
.terminus2049.github.io
.tew.org:80
.textnow.me
.thaicn.com:80
.thb.gov.tw
.theatrum-belli.com
.thebcomplex.com
.thebobs.com
.thebodyshop-usa.com
.thechinabeat.org:80
.thedalailamamovie.com:80
.thedw.us
.thefacebook.com
.thegly.com:80
.thehots.info:80
.thehun.net
.theinitium.com
.thenewslens.com
.thepiratebay.org
.theporndude.com
.theportalwiki.com
.thestandnews.com
.thetibetmuseum.org:80
.thetibetpost.com
.thetinhat.com
.thewgo.org
.theync.com:80
.thinkgeek.com
.thinkingtaiwan.com:80
.thinkwithgoogle.com
.thisav.com:80
.thlib.org:80
.thomasbernhard.org
.thongdreams.com:80
.throughnightsfire.com
.thumbzilla.com:80
.thywords.com
.thywords.com.tw:80
.tiananmenduizhi.com
.tiananmenuniv.com
.tiananmenuniv.net
.tiandixing.org
.tianhuayuan.com:80
.tianlawoffice.com:80
.tianti.io
.tiantibooks.org
.tianzhu.org:80
.tibet-envoy.eu
.tibet-foundation.org:80
.tibet-house-trust.co.uk:80
.tibet-initiative.de
.tibet-munich.de:80
.tibet.a.se:80
.tibet.at:80
.tibet.com
.tibet.net
.tibet.org
.tibet.sk:80
.tibet.to:80
.tibet3rdpole.org:80
.tibetaction.net
.tibetaid.org:80
.tibetan.fr:80
.tibetanaidproject.org:80
.tibetanarts.org:80
.tibetanbuddhistinstitute.org:80
.tibetancommunityuk.net:80
.tibetanjournal.com:80
.tibetanlanguage.org:80
.tibetanliberation.org
.tibetanpaintings.com:80
.tibetanphotoproject.com:80
.tibetanpoliticalreview.org:80
.tibetanreview.net:80
.tibetanwomen.org:80
.tibetanyouth.org:80
.tibetanyouthcongress.org
.tibetcharity.dk:80
.tibetchild.org:80
.tibetcity.com:80
.tibetcollection.com:80
.tibetcorps.org:80
.tibetexpress.net:80
.tibetgermany.com:80
.tibetgermany.de
.tibethaus.com:80
.tibetheritagefund.org:80
.tibethouse.us
.tibetinfonet.net:80
.tibetjustice.org:80
.tibetkomite.dk:80
.tibetnetwork.org
.tibetoffice.ch:80
.tibetoffice.com.au:80
.tibetonline.com
.tibetonline.tv
.tibetoralhistory.org:80
.tibetpolicy.eu:80
.tibetrelieffund.co.uk:80
.tibetsociety.com
.tibetsun.com:80
.tibetsupportgroup.org:80
.tibetswiss.ch:80
.tibettelegraph.com:80
.tibetwrites.org
.ticket.com.tw:80
.tigervpn.com
.tiltbrush.com
.timdir.com:80
.time.com:80
.timsah.com:80
.tinc-vpn.org
.tineye.com
.tiny.cc:80
.tinypaste.com
.tipo.gov.tw
.tistory.com:80
.tkcs-collins.com
.tma.co.jp
.tmagazine.com
.tmdfish.com:80
.tmpp.org:80
.tn1.shemalez.com
.tn2.shemalez.com
.tn3.shemalez.com
.tnaflix.com
.tngrnow.com:80
.tngrnow.net:80
.tnp.org:80
.to-porno.com
.toh.info:80
.tokyo-247.com:80
.tokyo-hot.com:80
.tokyo-porn-tube.com
.tokyocn.com
.tongil.or.kr:80
.tono-oka.jp:80
.toodoc.com:80
.top.tv
.top10vpn.com
.topbtc.com
.topnews.in:80
.toppornsites.com:80
.topshareware.com:80
.topsy.com
.toptip.ca
.torcn.com:80
.torguard.net
.torproject.org
.torrentprivacy.com
.torrenty.org
.torrentz.eu
.torvpn.com
.totalvpn.com
.toutiaoabc.com:80
.toutyrater.github.io
.toythieves.com:80
.tparents.org:80
.tpi.org.tw
.tracfone.com
.transparency.org
.treemall.com.tw
.trendsmap.com
.trialofccp.org
.trickip.net:80
.trickip.org:80
.trouw.nl:80
.trt.net.tr:80
.truebuddha-md.org:80
.truth101.co.tv:80
.truthontour.org:80
.truveo.com:80
.tryheart.jp
.tsctv.net:80
.tsdr.uspto.gov
.tsemtulku.com:80
.tsu.org.tw:80
.tt-rss.org
.tt1069.com
.tttan.com
.ttvnw.net
.tubaholic.com:80
.tube.com:80
.tube8.com
.tube911.com
.tubecup.com:80
.tubegals.com:80
.tubeislam.com:80
.tubepornclassic.com
.tubestack.com:80
.tubewolf.com
.tuibeitu.net:80
.tuidang.org
.tuidang.se:80
.tumblr.com
.tumutanzi.com:80
.tumview.com
.tunein.com:80
.tunnelbear.com
.tunnelr.com
.tuo8.blue
.tuo8.cc:80
.tuo8.club
.tuo8.fit
.tuo8.hk:80
.tuo8.in:80
.tuo8.ninja:80
.tuo8.org
.tuo8.pw:80
.tuo8.red
.tuo8.space:80
.turansam.org:80
.turbobit.net:80
.turbohide.com
.turbotwitter.com
.turntable.fm
.tushycash.com:80
.tuvpn.com
.tuzaijidi.com:80
.tv.com:80
.tvboxnow.com:80
.tvmost.com.hk:80
.tvplayvideos.com:80
.tvunetworks.com
.tw-blog.com:80
.tw-npo.org:80
.tw.iqiyi.com
.tw.jiepang.com
.tw.knowledge.yahoo.com
.tw.mall.yahoo.com
.tw.mobi.yahoo.com
.tw.news.yahoo.com
.tw01.org:80
.twaitter.com:80
.twapperkeeper.com
.twaud.io
.twavi.com:80
.twbbs.net.tw:80
.twblogger.com
.tweepguide.com
.tweeplike.me
.tweepml.org
.tweetbackup.com
.tweetboard.com
.tweetboner.biz
.tweetcs.com:80
.tweetdeck.com
.tweetedtimes.com
.tweetmylast.fm
.tweetphoto.com
.tweetrans.com
.tweetree.com
.tweettunnel.com
.tweetwally.com
.tweez.net:80
.twelve.today
.twerkingbutt.com
.twftp.org
.twgreatdaily.com
.twibble.de
.twibs.com
.twicountry.org:80
.twiends.com:80
.twifan.com:80
.twiffo.com
.twiggit.org
.twilightsex.com:80
.twimg.com
.twindexx.com
.twip.me
.twipple.jp
.twishort.com
.twister.net.co
.twisterio.com
.twit2d.com
.twitcause.com
.twitch.tv
.twitchcdn.net
.twitgether.com
.twitiq.com
.twitlonger.com
.twitoaster.com
.twitonmsn.com
.twitpic.com
.twitstat.com
.twitter.com
.twitter.jp
.twitter4j.org
.twittercounter.com
.twittergadget.com
.twitterkr.com
.twittermail.com
.twitterrific.com
.twittertim.es
.twitturk.com
.twitturly.com
.twitvid.com
.twitzap.com:80
.twnorth.org.tw:80
.twstar.net
.twtkr.com:80
.twttr.com
.twyac.org
.txxx.com:80
.tycool.com
.typepad.com
.u9un.com
.ubddns.org:80
.uberproxy.net
.uc-japan.org
.ucdc1998.org
.uderzo.it
.udn.com
.udn.com.tw
.uforadio.com.tw
.ug.m.wikipedia.org
.ugo.com:80
.uhdwallpapers.org
.uhrp.org
.uighur.nl
.ukliferadio.co.uk
.uku.im
.ulike.net:80
.ulop.net
.ultravpn.fr
.unblock-us.com
.unblock.cn.com
.unblockdmm.com:80
.unblocker.yt:80
.unblocksit.es
.underwoodammo.com
.unholyknight.com
.uni.cc:80
.unification.net:80
.unification.org.tw:80
.unirule.cloud
.unitedsocialpress.com:80
.unix100.com:80
.unknownspace.org
.unodedos.com:80
.unseen.is
.untraceable.us:80
.uocn.org
.updates.tdesktop.com
.upholdjustice.org:80
.upload4u.info:80
.upmedia.mg
.upornia.com:80
.uproxy.org
.upwill.org:80
.uraban.me
.urbansurvival.com
.urchin.com
.urlborg.com
.urlparser.com
.usacn.com
.usaip.eu
.usfk.mil
.usma.edu
.usmc.mil
.usno.navy.mil
.usocctn.com:80
.ustream.tv
.usunitednews.com:80
.utopianpal.com
.uu-gg.com:80
.uukanshu.com
.uvwxyz.xyz
.uwants.com:80
.uwants.net:80
.uyghuramerican.org
.uyghurcanadiansociety.org:80
.uyghurcongress.org
.uyghurensemble.co.uk:80
.uyghurpen.org:80
.uyghurpress.com:80
.uyghurstudies.org:80
.v2ex.com:80
.v2ray.com
.van001.com:80
.van698.com:80
.vanemu.cn:80
.vanilla-jp.com:80
.vanpeople.com:80
.vaticannews.va
.vatn.org
.vcf-online.org
.vcfbuilder.org
.vegas.williamhill.com
.vegasred.com
.velkaepocha.sk:80
.venbbs.com:80
.venchina.com:80
.venetianmacao.com
.ventureswell.com
.versavpn.com
.verybs.com
.vevo.com
.vft.com.tw:80
.viber.com
.vica.info:80
.victimsofcommunism.org:80
.vid.me
.vidble.com
.video.aol.com
.videobam.com
.videodetective.com:80
.videomega.tv
.videomo.com:80
.videopress.com
.vijayatemple.org:80
.vimeo.com
.vimperator.org
.vincnd.com
.vine.co
.vinniev.com
.vip-enterprise.com
.virtualrealporn.com
.vital247.org:80
.viu.com
.vivahentai4u.net:80
.vivatube.com:80
.vivthomas.com
.vizvaz.com:80
.vjav.com
.vjmedia.com.hk:80
.vllcs.org:80
.vmixcore.com
.vmpsoft.com
.vnet.link
.voacantonese.com
.voachinese.com
.voachineseblog.com
.voanews.com
.voatibetan.com
.voatibetanenglish.com
.vocativ.com:80
.vod-abematv.akamaized.net
.vod.wwe.com
.vot.org
.vovo2000.com:80
.voxer.com
.voy.com:80
.vpn.ac
.vpn.cjb.net
.vpn4all.com
.vpnaccount.org:80
.vpnaccounts.com
.vpncomparison.org:80
.vpncoupons.com:80
.vpncup.com
.vpndada.com
.vpnfan.com:80
.vpnfires.biz:80
.vpnforgame.net
.vpngate.jp
.vpngate.net
.vpngratis.net:80
.vpninja.net
.vpnintouch.com:80
.vpnintouch.net
.vpnjack.com
.vpnmaster.com
.vpnmentor.com
.vpnpick.com
.vpnpop.com
.vpnpronet.com
.vpnreactor.com
.vpnreviewz.com
.vpnsecure.me
.vpnshazam.com
.vpnshieldapp.com
.vpnsp.com:80
.vpntraffic.com:80
.vpntunnel.com
.vpnuk.info
.vpnunlimitedapp.com
.vpnvip.com
.vpnworldwide.com:80
.vporn.com
.vpser.net:80
.vrmtr.com:80
.vrsmash.com
.vtunnel.com
.vuku.cc
.vultryhw.com
.w3schools.com
.waffle1999.com
.wahas.com:80
.waigaobu.com:80
.wailaike.net:80
.waiwaier.com:80
.wallmama.com
.wallpapercasa.com
.wallproxy.com:80
.waltermartin.com
.waltermartin.org
.wanderinghorse.net
.wangafu.net
.wangjinbo.org
.wango.org
.wanz-factory.com
.warbler.iconfactory.net
.waselpro.com
.watch8x.com:80
.watchinese.com:80
.watchmygf.net
.wattpad.com
.wav.tv
.waveprotocol.org
.waymo.com
.wda.gov.tw
.wdf5.com:80
.wearehairy.com:80
.wearn.com
.web.dev
.web2project.net
.webevader.org:80
.webfreer.com:80
.webjb.org:80
.webmproject.org
.webrtc.org
.webrush.net:80
.webwarper.net:80
.weekmag.info:80
.wefightcensorship.org
.wefong.com:80
.wego.here.com
.weihuo.org:80
.weiming.info
.welovecock.com:80
.wemigrate.org:80
.wengewang.org
.wenhui.ch:80
.wenxuecity.com
.wenyunchao.com
.wenzhao.ca
.westca.com
.westernshugdensociety.org:80
.westernwolves.com
.westkit.net:80
.westpoint.edu
.wetplace.com:80
.wexiaobo.org
.wezone.net
.wforum.com
.wha.la:80
.whatblocked.com
.whatbrowser.org
.whatsapp.com
.whatsapp.net
.whatsonweibo.com
.wheatseeds.org:80
.wheelockslatin.com
.whereiswerner.com
.wheretowatch.com
.whippedass.com:80
.whodns.xyz:80
.whoer.net
.whyx.org
.widevine.com
.wikaba.com:80
.wiki.jqueryui.com
.wiki.oauth.net
.wiki.phonegap.com
.wikileaks-forum.com:80
.wikileaks.ch
.wikileaks.com
.wikileaks.de
.wikileaks.eu
.wikileaks.lu
.wikileaks.org
.wikileaks.pl
.wikimapia.org
.wikiwiki.jp
.williamhill.com:80
.willw.net
.windowsphoneme.com
.windscribe.com
.wingamestore.com
.wingy.site
.wire.com
.wiredbytes.com
.wiredpen.com
.wisdompubs.org:80
.wisevid.com
.withgoogle.com
.withyoutube.com
.witnessleeteaching.com:80
.witopia.net:80
.wizcrafts.net
.wjbk.org
.wlx.sowiki.net
.wnacg.com:80
.wnacg.org:80
.wo.tc:80
.wo3ttt.wordpress.com
.woeser.com
.wokar.org:80
.wolfax.com
.woolyss.com
.woopie.jp
.woopie.tv
.wordpress.com:80
.workatruna.com
.workerdemo.org.hk:80
.workerempowerment.org:80
.workersthebig.net
.worldcat.org:80
.worldvpn.net
.wow-life.net:80
.wow.com:80
.wowgirls.com
.wowlegacy.ml
.wowporn.com
.wowrk.com:80
.woyaolian.org:80
.wp.com
.wpoforum.com
.wqyd.org
.wsj.com
.wsj.net
.wsjhk.com:80
.wtbn.org:80
.wtfpeople.com:80
.wufafangwen.com
.wuguoguang.com
.wujieliulan.com
.wuw.red
.wuyanblog.com
.wwitv.com
.www.ajsands.com
.www.klip.me
.www.linksalpha.com
.www.moztw.org
.www.powerpointninja.com
.www.shadowsocks.com
.www.shwchurch.org
.www.wan-press.org
.www1.biz:80
.wwwhost.biz:80
.x-art.com
.x-berry.com
.x-wall.org
.x.company
.x24hr.com:80
.xbabe.com
.xbookcn.com
.xbtce.com
.xcafe.in
.xcity.jp
.xcritic.com:80
.xerotica.com:80
.xfinity.com
.xfm.pp.ru:80
.xgmyd.com
.xhamster.com
.xianba.net:80
.xianchawang.net:80
.xianjian.tw:80
.xianqiao.net:80
.xiaobaiwu.com:80
.xiaochuncnjp.com:80
.xiaod.in:80
.xiaohexie.com
.xiaolan.me
.xiaoma.org
.xihua.es:80
.xijie.wordpress.com
.xing.com:80
.xinmiao.com.hk
.xiongpian.com:80
.xiuren.org:80
.xjp.cc
.xjtravelguide.com
.xkiwi.tk:80
.xlfmwz.info
.xm.com
.xml-training-guide.com
.xn--4gq171p.com
.xn--czq75pvv1aj5c.org
.xn--i2ru8q2qg.com
.xn--ngstr-lra8j.com
.xn--oiq.cc
.xn--p8j9a0d9c9a.xn--q9jyb4c
.xnxx.com
.xpud.org
.xrentdvd.com:80
.xskywalker.com
.xskywalker.net:80
.xtube.com
.xuchao.net
.xuchao.org
.xuehua.us
.xvideos.com
.xvideos.es
.xxbbx.com:80
.xxlmovies.com:80
.xxuz.com:80
.xxx.com
.xxx.xxx:80
.xxxfuckmom.com:80
.xxxx.com.au
.xxxy.biz:80
.xxxy.info:80
.xxxymovies.com:80
.yahoo.com.hk
.yakbutterblues.com
.yam.com
.yam.org.tw
.yanghengjun.com:80
.yasni.co.uk
.ydy.com:80
.yeahteentube.com
.yecl.net
.yeelou.com
.yegle.net
.yes-news.com
.yes.xxx:80
.yes123.com.tw
.yesasia.com
.yesasia.com.hk
.yespornplease.com
.ygto.com:80
.yhcw.net
.yibada.com:80
.yibaochina.com:80
.yidio.com
.yingsuoss.com:80
.yipub.com
.yizhihongxing.com:80
.yobit.net
.yobt.com:80
.yobt.tv
.yogichen.org
.yolasite.com:80
.yomiuri.co.jp:80
.yorkbbs.ca:80
.you-get.org
.youdontcare.com:80
.youjizz.com
.youmaker.com
.youngpornvideos.com:80
.youpai.org
.youporn.com
.youporngay.com
.your-freedom.net:80
.yourepeat.com
.yourlisten.com:80
.yourlust.com:80
.yourprivatevpn.com
.yourtrap.com:80
.yousendit.com
.youtu.be
.youtube-nocookie.com
.youtube.com
.youtubecn.com:80
.youtubeeducation.com
.youtubegaming.com
.youversion.com
.youwin.com
.youxu.info
.yt.be
.ytimg.com
.ytn.co.kr
.yuanzhengtang.org:80
.yulghun.com:80
.yunchao.net
.yuntipub.com
.yuvutu.com:80
.yvesgeleyn.com
.yyii.org
.yzzk.com:80
.zalmos.com
.zannel.com
.zaobao.com
.zaobao.com.sg
.zaozon.com:80
.zapto.org:80
.zattoo.com
.zb.com
.zdnet.com.tw
.zello.com
.zengjinyan.org:80
.zenmate.com
.zenmate.com.ru
.zeronet.io
.zeutch.com
.zfreet.com:80
.zgsddh.com:80
.zh.bitterwinter.org
.zh.wikinews.org
.zhanbin.net
.zhangboli.net:80
.zhangtianliang.com
.zhanlve.org
.zhao.1984.city
.zhengjian.org
.zhenlibu.info
.zhenlibu1984.com
.zhinengluyou.com:80
.zhongguotese.net
.zhongmeng.org
.zhoushuguang.com:80
.zhreader.com
.zhuangbi.me
.zhuanxing.cn:80
.zhuatieba.com
.zhuichaguoji.org
.zillionk.com
.zim.vn
.zinio.com
.ziporn.com:80
.zippyshare.com:80
.zkaip.com
.zmw.cn
.zodgame.us:80
.zonaeuropa.com
.zonghexinwen.com
.zonghexinwen.net:80
.zoogvpn.com
.zootool.com
.zoozle.net:80
.zorrovpn.com
.zozotown.com
.zpn.im
.zspeeder.me
.zsrhao.com:80
.zuo.la
.zuobiao.me
.zuola.com
.zvereff.com
.zynaima.com:80
.zynamics.com
.zyns.com:80
.zzcartoon.com:80
.zzcloud.me
.zzux.com:80
123rf.com:80
14.102.250.18
14.102.250.19
174.142.105.153
18onlygirls.com:80
1989report.hkja.org.hk:80
21sextury.com:80
24smile.org:80
2lipstube.com:80
30boxes.com:80
3arabtv.com:80
50.7.31.230:8898
56cun04.jigsy.com:80
5aimiku.com:80
5i01.com:80
64tianwang.com:80
64wiki.com:80
666kb.com:80
67.220.91.15
67.220.91.18
67.220.91.23
69.65.19.160
72.52.81.22
85.17.73.31:80
85cc.net:80
85st.com:80
89.64.charter.constitutionalism.solutions:80
908taiwan.org:80
a5.com.ru:80
aamacau.com:80
abclite.net:80
ac.jiruan.net:80
actfortibet.org:80
actimes.com.au:80
adult.friendfinder.com:80
adultfriendfinder.com:80
ae.hao123.com:80
ai-wen.net:80
aiss.anws.gov.tw:443
aiweiwei.com:80
alexlur.org:80
aliengu.com:80
allgirlsallowed.org:80
alliance.org.hk:80
alvinalexander.com:80
animecrazy.net:80
anontext.com:80
anonymise.us:80
antichristendom.com:80
api.proxlet.com:80
apk-dl.com:80
app.heywire.com:80
ar.hao123.com:80
archive.today:443
archive.today:80
artofpeacefoundation.org:80
artsy.net:80
asg.to:80
asianews.it:80
atgfw.org:80
av.nightlife141.com:80
azerimix.com:80
babynet.com.hk:80
backtotiananmen.com:80
badoo.com:80
bartvpn.com:80
bbc.in:80
bbs-tw.com:80
bbs.brockbbs.com:80
bbs.cantonese.asia:80
bbs.ecstart.com:80
bbs.hanminzu.org:80
bbs.hasi.wang:80
bbs.huasing.org:80
bbs.kimy.com.tw:80
bbs.mikocon.com:80
bbs.morbell.com:80
bbs.netbig.com:80
bbs.ozchinese.com:80
bbs.qmzdd.com:80
bbs.sina.com:80
bbs.skykiwi.com:80
bbs.sou-tong.org:80
bbs.tuitui.info:80
bbsland.com:80
bbtoystore.com:80
bdsmvideos.net:80
bemywife.cc:80
beric.me:80
biantailajiao.com:80
biantailajiao.in:80
bigfools.com:80
bipic.net:80
bitsnoop.com:80
bizhat.com:80
blewpass.com:80
blinw.com:80
blog.calibre-ebook.com:80
blog.cnyes.com:80
blog.excite.co.jp:80
blog.foolsmountain.com:80
blog.inoreader.com:80
blog.jackjia.com:80
blog.lester850.info:80
blog.martinoei.com:80
blog.ranxiang.com:80
blog.sina.com.tw:80
blog.sogoo.org:80
blog.soylent.com:80
blog.taragana.com:80
blog.xuite.net:80
blog.youthwant.com.tw:80
blogimg.jp:80
blogs.yahoo.co.jp:80
blogspot.com:80
blogtd.net:80
blueangellive.com:80
bolin.netfirms.com:80
bonbonme.com:80
book.zi5.me:80
bookepub.com:80
boyangu.com:80
br.hao123.com:80
breaking911.com:80
broadbook.com:80
brucewang.net:80
btdigg.org:80
bunbunhk.com:80
busytrade.com:80
bwsj.hk:80
c1522.mooo.com:80
canadameet.com:80
cardinalkungfoundation.org:80
cari.com.my:80
carmotorshow.com:80
cclife.org:80
cclifefl.org:80
ccue.ca:80
ccue.com:80
cdn*.search.xxx:80
cdn*.xda-developers.com:80
cdn1.lp.saboom.com:80
cdp1989.org:80
cdpeu.org:80
cdpusa.org:80
certificate.revocationcheck.com:80
ch.shvoong.com:80
chengmingmag.com:80
chicagoncmtv.com:80
china-mmm.jp.net:80
china-mmm.sa.com:80
china.hket.com:80
china.ucanews.com:80
chinaaid.net:80
chinaaid.org:80
chinaaid.us:80
chinageeks.org:80
chinalaborwatch.org:80
chinalawandpolicy.com:80
chinalawtranslate.com:80
chinamz.org:80
chinatweeps.com:80
chinaway.org:80
chinayouth.org.hk:80
chinese-leaders.org:80
chinese-memorial.org:80
chinese.donga.com:80
chinese.engadget.com:80
chinese.irib.ir:80
chinese.soifind.com:80
chithu.org:80
chn.chosun.com:80
christiantimes.org.hk:80
chubun.com:80
chuizi.net:80
citizenlab.org:80
citizensradio.org:80
city9x.com:80
cl.d0z.net:80
clearharmony.net:80
clearwisdom.net:80
cling.omy.sg:80
clinica-tibet.ru:80
cloakpoint.com:80
cmi.org.tw:80
cmp.hku.hk:80
cn.calameo.com:80
cn.dayabook.com:80
cn.fmnnow.com:80
cn.freeones.com:80
cn.giganews.com:80
cn.ibtimes.com:80
cn.nytstyle.com:80
cn.shafaqna.com:80
cn.thegay.com:80
cn.uncyclopedia.wikia.com:80
cn.voa.mobi:80
cn2.streetvoice.com:80
commandarms.com:80
corumcollege.com:80
cosmic.monar.ch:80
crd-net.org:80
cts.com.tw:80
cyberghost.natado.com:80
cytode.us:80
d1b183sg0nvnuh.cloudfront.net:443
d1b183sg0nvnuh.cloudfront.net:80
d1c37gjwa26taa.cloudfront.net:443
d1c37gjwa26taa.cloudfront.net:80
d3c33hcgiwev3.cloudfront.net:443
d3c33hcgiwev3.cloudfront.net:80
dabr.eu:80
dafagood.com:80
dafahao.com:80
dailynews.sina.com:80
daiphapinfo.net:80
dajiyuan.eu:80
dajusha.baywords.com:80
dalailama.com:80
dalailama.usc.edu:80
dalailama80.org:80
dalailamafellows.org:80
danbooru.donmai.us:80
daodu14.jigsy.com:80
daolan.net:80
darktoy.net:80
dcmilitary.com:80
deck.ly:80
dfn.org:80
dharmakara.net:80
digiland.tw:80
disp.cc:80
djangosnippets.org:80
doctorvoice.org:80
domainhelp.search.com:80
dowei.org:80
download.aircrack-ng.org:80
download.cnet.com:80
download.ithome.com.tw:80
dphk.org:80
drsunacademy.com:80
duping.net:80
dupola.com:80
dupola.net:80
dynupdate.no-ip.com:80
e-info.org.tw:80
eastern-ark.com:80
ebookbrowse.com:80
ebookee.com:80
echofon.com:80
ecministry.net:80
ecsm.vs.com:80
edicypages.com:80
edoors.com:80
efcc.org.hk:80
electionsmeter.com:80
emilylau.org.hk:80
en.favotter.net:80
en.hao123.com:80
englishforeveryone.org:80
englishpen.org:80
epochtimes.de:80
epochtimes.fr:80
epochtimes.jp:80
epochtimes.ru:80
epochtimes.se:80
epochtimestr.com:80
erabaru.net:80
etaiwannews.com:80
etvonline.hk:80
evchk.wikia.com:80
experts-univers.com:80
facesoftibetanselfimmolators.info:80
fail.hk:80
falun-co.org:80
falun-ny.net:80
falun.caltech.edu:80
falunart.org:80
falunau.org:80
falundafa-dc.org:80
falundafa.org:80
falundafamuseum.org:80
falungong.org.uk:80
faluninfo.de:80
faluninfo.net:80
familyfed.org:80
fangong.forums-free.com:80
fangongheike.com:80
fanqiangyakexi.net:80
fapdu.com:80
faproxy.com:80
fbcdn*.akamaihd.net:443
fc2blog.net:80
feeds.fileforum.com:80
feer.com:80
feitianacademy.org:80
ff.im:80
fffff.at:80
fflick.com:80
fgmtv.net:80
fillthesquare.org:80
filmingfortibet.org:80
findmespot.com:80
finler.net:80
fleshbot.com:80
flickrhivemind.net:80
fofldfradio.org:80
footwiball.com:80
forum.baby-kingdom.com:80
forum.cyberctm.com:80
forum.idsam.com:80
forum.my903.com:80
forum.mymaji.com:80
forum.omy.sg:80
forum.palmislife.com:80
forum.setty.com.tw:80
forum.sina.com.hk:80
forum.slime.com.tw:80
forum.tvb.com:80
foxgay.com:80
foxtang.com:80
fq.wikia.com:80
fqok.org:80
free-gate.org:80
free-proxy.cz:80
freechina.net:80
freeilhamtohti.org:80
freeman2.com:80
freemoren.com:80
freemorenews.com:80
freenet-china.org:80
freenewscn.com:80
freevpn.nl:80
freeyellow.com:80
friendfeed.com:80
friends-of-tibet.org:80
fucd.com:80
fuckgfw.org:80
fulue.com:80
funp.com:80
fzh999.com:80
fzh999.net:80
fzlm.com:80
gamebase.com.tw:80
gamejolt.com:80
ganges.com:80
gardennetworks.com:80
gati.org.tw:80
gdzf.org:80
geocities.jp:80
getiton.com:80
gfbv.de:80
gfw.org.ua:80
gigporno.ru:80
gist.github.com:443
globaljihad.net:80
globalmediaoutreach.com:80
globalmuseumoncommunism.org:80
gloryhole.com:80
gmbd.cn:80
go-pki.com:80
goagent.codeplex.com:80
gobet.cc:80
godns.work:80
godsdirectcontact.co.uk:80
godsdirectcontact.org.tw:80
gojet.krtco.com.tw:80
gongm.in:80
gongmeng.info:80
gongminliliang.com:80
google.calstate.edu:80
grandtrial.org:80
great-firewall.com:80
great-roc.org:80
greatfirewall.biz:80
greatroc.org:80
greatzhonghua.org:80
gs-discuss.com:80
guancha.org:80
guaneryu.com:80
gunsandammo.com:80
guruonline.hk:80
gvlib.com:80
h1n1china.org:80
hahaxixi.github.io:443
hahaxixi.github.io:80
hahlo.com:80
have8.com:80
heix.pp.ru:80
hentaitube.tv:80
heqinglian.net:80
hi-on.org.tw:80
hideme.nl:80
highpeakspureearth.com:80
himalayanglacier.com:80
hizb-ut-tahrir.info:80
hizb-ut-tahrir.org:80
hizbuttahrir.org:80
hk-pub.com:80
hk.geocities.com:80
hk.gradconnection.com:80
hk.hao123img.com:80
hk.knowledge.yahoo.com:80
hk.myblog.yahoo.com:80
hk.rd.yahoo.com:80
hk.yahoo.com:80
hkbc.net:80
hkci.org.hk:80
hkcoc.weather.com.hk:80
hkday.net:80
hkdf.org:80
hkfreezone.com:80
hkfront.org:80
hkhkhk.com:80
hkhrc.org.hk:80
hkhrm.org.hk:80
hkjc.com:80
hkptu.org:80
hkreporter.loved.hk:80
hkupop.hku.hk:80
holymountaincn.com:80
home.sina.com:80
homeservershow.com:80
hongmeimei.com:80
hotfrog.com.tw:80
hotgoo.com:80
hotpot.hk:80
hqmovies.com:80
hrweb.org:80
hst.net.tw:80
ht.ly:80
htl.li:80
huaxia-news.com:80
huaxiabao.org:80
huaxin.ph:80
huiyi.in:80
humanrightsbriefing.org:80
hurgokbayrak.com:80
hustlercash.com:80
hutong9.net:80
huyandex.com:80
hxwq.org:80
ibros.org:80
icams.com:80
ice.audionow.com:80
id.hao123.com:80
idemocracy.asia:80
if.ttt:80
ifanqiang.com:80
ifjc.org:80
iipdigital.usembassy.gov:80
imageshack.us:80
img.dlsite.jp:80
impact.org.au:80
impp.mn:80
in-disguise.com:80
in99.org:80
info-graf.fr:80
internet.org:80
internetdefenseleague.org:80
internetfreedom.org:80
ipalter.com:80
iredmail.org:80
isohunt.com:80
isunaffairs.com:80
isuntv.com:80
ithelp.ithome.com.tw:80
jamaat.org:80
japanfirst.asianfreeforum.com:80
jbtalks.cc:80
jbtalks.com:80
jbtalks.my:80
jeanyim.com:80
jieshibaobao.com:80
jigong1024.com:80
jihadintel.meforum.org:80
jinpianwang.com:80
jjgirls.com:80
jkforum.net:80
jp.hao123.com:80
jpopforum.net:80
justfreevpn.com:80
justpaste.it:80
justtristan.com:80
juyuange.org:80
kanzhongguo.com:80
kanzhongguo.eu:80
karkhung.com:80
kineox.free.fr:80
kinghost.com:80
kiwi.kz:80
kun.im:80
kusocity.com:80
kwongwah.com.my:80
kyohk.net:80
la-forum.org:80
ladbrokes.com:80
lamrim.com:80
laomiu.com:80
latelinenews.com:80
ld.hao123img.com:80
lefora.com:80
leirentv.ca:80
leisurecafe.ca:80
library.usc.cuhk.edu.hk:80
limiao.net:80
linkuswell.com:80
listorious.com:80
lizhizhuangbi.com:80
lkcn.net:80
localpresshk.com:80
logbot.net:80
lsforum.net:80
luxebc.com:80
m.hkgalden.com:443
m.hkgalden.com:80
m.slandr.net:80
ma.hao123.com:80
macts.com.tw:80
mahabodhi.org:80
makkahnewspaper.com:80
manicur4ik.ru:80
marguerite.su:80
mash.to:80
maskedip.com:80
maturejp.com:80
mayimayi.com:80
mcfog.com:80
mcreasite.com:80
me.youthwant.com.tw:80
mefeedia.com:80
megavideo.com:80
meirixiaochao.com:80
meme.yahoo.com:80
memorybbs.com:80
merit-times.com.tw:80
meshrep.com:80
meyou.jp:80
mhradio.org:80
michaelanti.com:80
middle-way.net:80
mihua.org:80
mimiai.net:80
minghui-a.org:80
minghui-b.org:80
minghui-school.org:80
mingjingnews.com:80
mingpaonews.com:80
minzhuzhanxian.com:80
minzhuzhongguo.org:80
mirrorbooks.com:80
mitbbsau.com:80
mixpod.com:80
mjlsh.usc.cuhk.edu.hk:80
mnewstv.com:80
mo.nightlife141.com:80
moby.to:80
molihua.org:80
motor4ik.ru:80
mp3ye.eu:80
mpfinance.com:80
mpinews.com:80
mponline.hk:80
msguancha.com:80
muchosucko.com:80
multiproxy.org:80
multiupload.com:80
mx.hao123.com:80
my.mail.ru:80
myshare.url.com.tw:80
mysinablog.com:80
mysite.verizon.net:80
namgyalmonastery.org:80
naweeklytimes.com:80
nccwatch.org.tw:80
netcolony.com:80
netsneak.com:80
networkedblogs.com:80
neverforget8964.org:80
new-3lunch.net:80
newcenturynews.com:80
newipnow.com:80
news.cnyes.com:80
news.hk.msn.com:80
news.hkpeanut.com:80
news.msn.com.tw:80
news.omy.sg:80
news.seehua.com:80
news.sina.com.hk:80
news.sina.com.tw:80
news.sinchew.com.my:80
news.singtao.ca:80
news.tvbs.com.tw:80
news100.com.tw:80
newschinacomment.org:80
newstarnet.com:80
newyorktimes.com:80
nexttv.com.tw:80
ngensis.com:80
ninecommentaries.com:80
nintendium.com:80
nlfreevpn.com:80
noodlevpn.com:80
ntdtv.ca:80
ntdtv.org:80
ntdtv.ru:80
ntdtvla.com:80
nuzcom.com:80
ny.stgloballink.com:80
ny.visiontimes.com:80
nyaa.eu:80
nylon-angel.com:80
nylonstockingsonline.com:80
nytchina.com:80
nyti.ms:80
observechina.net:80
ocaspro.com:80
occupytiananmen.com:80
oclp.hk:80
offbeatchina.com:80
officeoftibet.com:80
ofile.org:80
oizoblog.com:80
okk.tw:80
old-cat.net:80
old.nabble.com:80
omgili.com:80
online.recoveryversion.org:80
onmoon.com:80
onmoon.net:80
open.com.hk:80
openallweb.com:80
opml.radiotime.com:80
organharvestinvestigation.net:80
oursogo.com:80
owl.li:80
oyax.com:80
page.bid.yahoo.com:80
page2rss.com:80
paljorpublications.com:80
panamapapers.sueddeutsche.de:80
paper.li:80
paperb.us:80
pastebin.com:80
pbwiki.com:80
pcdvd.com.tw:80
pcij.org:80
pdetails.com:80
peacefire.org:80
pearlher.org:80
penchinese.com:80
pengyulong.com:80
penisbot.com:80
perfectvpn.net:80
pfd.org.hk:80
phapluan.org:80
phayul.com:80
philborges.com:80
philly.com:80
pictures.playboy.com:80
picturesocial.com:80
pioneer-worker.forums-free.com:80
piraattilahti.org:80
plays.com.tw:80
plm.org.hk:80
plunder.com:80
pobieramy.top:80
politicalchina.org:80
politicalconsultation.org:80
postadult.com:80
provideocoalition.com:80
proxifier.com:80
proxyanonimo.es:80
proxyroad.com:80
prozz.net:80
psiphon.civisec.org:80
pubu.com.tw:80
puffinbrowser.com:80
pulse.yahoo.com:80
pwned.com:80
python.com:80
qixianglu.cn:80
quantumbooter.net:80
qusi8.net:80
qxbbs.org:80
radiko.jp:80
radioaustralia.net.au:80
raindrop.io:443
rangwang.biz:80
rangzen.com:80
rangzen.net:80
rangzen.org:80
rapidgator.net:80
rcinet.ca:80
rconversation.blogs.com:80
realforum.zkiz.com:80
redballoonsolidarity.org:80
redchinacn.org:80
redtube.com:80
relaxbbs.com:80
religioustolerance.org:80
retweetist.com:80
revver.com:80
rfalive1.akacast.akamaistream.net:80
rfaweb.org:80
rfi.my:80
riku.me:80
riseup.net:443
rthklive2-lh.akamaihd.net:80
rukor.org:80
rutube.ru:80
s3-ap-northeast-1.amazonaws.com:80
sa.hao123.com:80
sapikachu.net:80
savemedia.com:80
savetibet.fr:80
savetibet.nl:80
savetibet.ru:80
savevid.com:80
seapuff.com:80
search.disconnect.me:443
secure.hustler.com:80
securityinabox.org:443
securityinabox.org:80
seesmic.com:80
sejie.com:80
shadow.ma:80
shapeservices.com:80
share.dmhy.org:80
share.youthwant.com.tw:80
sheikyermami.com:80
shenyun.com:80
shinychan.com:80
shipcamouflage.com:80
showbiz.omy.sg:80
simpleproductivityblog.com:80
sino-monthly.com:80
sinocism.com:80
sinomontreal.ca:80
sipml5.org:80
sis.xxx:80
sis001.us:80
smchbooks.com:80
smhric.org:80
sneakme.net:80
snowlionpub.com:80
socialwhale.com:80
softwaredownload.gitbooks.io:80
sokamonline.com:80
southnews.com.tw:80
sowers.org.hk:80
specxinzl.jigsy.com:80
spem.at:80
ss*.4sqi.net:443
ss.carryzhou.com:80
ss.pythonic.life:80
ssglobal.co:80
static01.nyt.com:80
stranabg.com:80
stupidvideos.com:80
subacme.rerouted.org:80
summify.com:80
sun1911.com:80
sysresccd.org:80
sytes.net:80
tabtter.jp:80
tahr.org.tw:80
taiwan-sex.com:80
taiwankiss.com:80
taiwannation.50webs.com:80
taiwannation.com.tw:80
taiwannation.com:80
taiwantp.net:80
taiwanus.net:80
taiwanyes.com:80
taiwanyes.ning.com:80
tangben.com:80
tarr.uspto.gov:80
tbs-rainbow.org:80
tbskkinabalu.page.tl:80
tbswd.org:80
tchrd.org:80
tcnynj.org:80
teamamericany.com:80
teensinasia.com:80
th.hao123.com:80
theblemish.com:80
thecenter.mit.edu:80
thegioitinhoc.vn:80
thehousenews.com:80
thereallove.kr:80
therock.net.nz:80
thespeeder.com:80
thetibetcenter.org:80
thetibetconnection.org:80
thetrotskymovie.com:80
thevivekspot.com:80
threatchaos.com:80
tiananmenmother.org:80
tianyantong.org.cn:80
tibet-info.net:80
tibet.ca:80
tibet.fr:80
tibet.nu:80
tibet.org.tw:80
tibetalk.com:80
tibetan-alliance.org:80
tibetancommunity.org:80
tibetanculture.org:80
tibetanfeministcollective.org:80
tibetansports.org:80
tibetcharity.in:80
tibetfocus.com:80
tibetfund.org:80
tibethouse.jp:80
tibethouse.org:80
tibetlibre.free.fr:80
tibetmuseum.org:80
tibetoffice.eu:80
tibetoffice.org:80
tibetsites.com:80
tibettimes.net:80
times.hinet.net:80
tintuc101.com:80
tinychat.com:80
tl.gd:80
tmi.me:80
togetter.com:80
tonyyan.net:80
toonel.net:80
top81.ws:80
topic.youthwant.com.tw:80
tor.blingblingsquad.net:80
tor.cn.uptodown.com:80
tor.updatestar.com:80
tora.to:80
torrentproject.se:80
tosh.comedycentral.com:80
towngain.com:80
toypark.in:80
toytractorshow.com:80
traffichaus.com:80
trtc.com.tw:80
trulyergonomic.com:80
tsquare.tv:80
tsunagarumon.com:80
tu8964.com:80
tui.orzdream.com:80
tuidang.net:80
tuitwit.com:80
tuzaijidi.com:80
tvants.com:80
tvider.com:80
tw-blog.com:443
tw.answers.yahoo.com:443
tw.answers.yahoo.com:80
tw.bid.yahoo.com:443
tw.bid.yahoo.com:80
tw.gigacircle.com:80
tw.hao123.com:80
tw.money.yahoo.com:80
tw.myblog.yahoo.com:80
tw.streetvoice.com:80
tw.tomonews.net:80
tw.voa.mobi:80
tw.yahoo.com:80
twbbs.org:80
twbbs.tw:80
tweepmag.com:80
tweets.seraph.me:80
tweetymail.com:80
twibase.com:80
twibbon.com:80
twicsy.com:80
twilog.org:80
twimbow.com:80
twistar.cc:80
twisternow.com:80
twistory.net:80
twitbrowser.net:80
twitgoo.com:80
twitmania.com:80
twittbot.net:80
twitterfeed.com:80
twitthat.com:80
twiyia.com:80
twskype.com:80
twt.tl:80
twtr2src.ogaoga.org:80
twtrland.com:80
twurl.nl:80
ub0.cc:80
ufreevpn.com:80
uighur.narod.ru:80
uighurbiz.net:80
ukcdp.co.uk:80
ultraxs.com:80
uncyclomedia.org:80
uncyclopedia.hk:80
uncyclopedia.tw:80
unpo.org:80
upcoming.yahoo.com:80
ur7s.com:80
us.to:80
userapi.nytlog.com:80
ushuarencity.echainhost.com:80
usinfo.state.gov:80
usus.cc:80
uyghur-j.org:80
uyghur.co.uk:80
uyghurpress.com:443
uygur.fc2web.com:80
uygur.org:80
uymaarip.com:80
vansky.com:80
vds.rightster.com:80
veoh.com:80
vermonttibet.org:80
video.ap.org:80
video.fdbox.com:80
video.foxbusiness.com:80
video.pbs.org:80
video.yahoo.com:80
videopediaworld.com:80
vietdaikynguyen.com:80
visibletweets.com:80
vlog.xuite.net:80
vn.hao123.com:80
voa-11.akacast.akamaistream.net:80
voagd.com:80
vocn.tv:80
vpn.cmu.edu:80
vpn.sv.cmu.edu:80
vpnbook.com:80
vpnfire.com:80
vpnhq.com:80
vraiesagesse.net:80
wallornot.org:80
wanglixiong.com:80
wangruoshui.net:80
want-daily.com:80
washeng.net:80
webbang.net:80
weblagu.com:80
webs-tv.net:80
website.informer.com:80
webworkerdaily.com:80
weiboleak.com:80
weiboscope.jmsc.hku.hk:80
weijingsheng.org:80
weiquanwang.org:80
weisuo.ws:80
wengewang.com:80
wetpussygames.com:80
wezhiyong.org:80
whitebear.freebearblog.org:80
whotalking.com:80
whylover.com:80
wiki.cnitter.com:80
wiki.gamerp.jp:80
wiki.moegirl.org:80
wildammo.com:80
winning11.com:80
winwhispers.info:80
wlcnew.jigsy.com:80
wn.com:80
woesermiddle-way.net:80
worldjournal.com:80
woxinghuiguo.com:80
wozy.in:80
wrchina.org:80
wretch.cc:80
writer.zoho.com:80
wsgzao.github.io:443
wsgzao.github.io:80
wuerkaixi.com:80
wufi.org.tw:80
wujie.net:80
wukangrui.net:80
wuu.wikipedia.org:443
wuu.wikipedia.org:80
www.abclite.net:443
www.americorps.gov:80
www.antd.org:80
www.aolnews.com:80
www.citizenlab.org:80
www.cmoinc.org:80
www.dwheeler.com:80
www.eastturkistan.net:80
www.ftchinese.com:443
www.gmiddle.com:80
www.gmiddle.net:80
www.hustlercash.com:80
www.idlcoyote.com:80
www.kindleren.com:80
www.lamenhu.com:80
www.m-sport.co.uk:80
www.metro.taipei:80
www.monlamit.org:80
www.orchidbbs.com:80
www.owind.com:80
www.oxid.it:80
www.s4miniarchive.com:80
www.tablesgenerator.com:80
www.taiwanonline.cc:80
www.taup.org.tw:80
www.wangruowang.org:80
www.websnapr.com:80
www.zensur.freerk.com:80
x1949x.com:80
x365x.com:80
xa.yimg.com:80
xanga.com:80
xiezhua.com:80
xinhuanet.org:80
xinqimeng.over-blog.com:80
xinsheng.net:80
xinshijue.com:80
xinyubbs.net:80
xizang-zhiye.org:80
xlfmtalk.com:80
xmovies.com:80
xpdo.net:80
xuzhiyong.net:80
xvideo.cc:80
xys.dxiong.com:80
xys.org:80
xysblogs.org:80
xyy69.com:80
xyy69.info:80
yangjianli.com:80
yeeyi.com:80
yeyeclub.com:80
yilubbs.com:80
yong.hu:80
youngspiration.hk:80
youshun12.com:80
ytht.net:80
yuanming.net:80
yx51.net:80
zacebook.com:80
zgzcjj.net:80
zh-yue.wikipedia.org:443
zh-yue.wikipedia.org:80
zh.ecdm.wikia.com:80
zh.m.wikipedia.org:443
zh.m.wikipedia.org:80
zh.pokerstrategy.com:80
zh.uncyclopedia.wikia.com:80
zh.wikipedia.org:443
zh.wikipedia.org:80
zh.wikisource.org:80
zhao.jinhai.de:80
zhenghui.org:80
zhengwunet.org:80
zhenxiang.biz:80
zhongguo.ca:80
zhongguorenquan.org:80
zomobo.net:80
zyzc9.com:80
{-forward-override}
.aftygh.gov.tw
.aide.gov.tw
.aliyun.com
.arte.gov.tw
.baidu.com
.bianlei.com
.chinaso.com
.chinaz.com
.chukuang.gov.tw
.clientservices.googleapis.com
.cn.gravatar.com
.connectivitycheck.gstatic.com
.cromotc.nat.gov.tw
.csi.gstatic.com
.cwb.gov.tw
.cycab.gov.tw
.dbnsa.gov.tw
.df.gov.tw
.dl.google.com
.download.syniumsoftware.com
.eastcoast-nsa.gov.tw
.erv-nsa.gov.tw
.fonts.googleapis.com
.fonts.gstatic.com
.gov.cn
.grb.gov.tw
.gysd.nyc.gov.tw
.haosou.com
.haygo.com
.hchcc.gov.tw
.hiwifi.com
.hsinchu-cc.gov.tw
.http2.golang.org
.iner.gov.tw
.ip.cn
.ip6.static.sl-reverse.com
.jike.com
.jpush.cn
.kh.google.com
.khm.google.com
.khm.googleapis.com
.khm0.google.com
.khm0.googleapis.com
.khm1.google.com
.khm1.googleapis.com
.khm2.google.com
.khm2.googleapis.com
.khm3.google.com
.khm3.googleapis.com
.khmdb.google.com
.khmdb.googleapis.com
.klsio.gov.tw
.kmseh.gov.tw
.lungtanhr.gov.tw
.maolin-nsa.gov.tw
.matsu-news.gov.tw
.matsu-nsa.gov.tw
.matsucc.gov.tw
.moe.gov.tw
.music.jwmusic.org
.mvdis.gov.tw
.myvlog.im.tv
.nankan.gov.tw
.ncree.gov.tw
.necoast-nsa.gov.tw
.ner.gov.tw
.nmmba.gov.tw
.nmp.gov.tw
.nmvttc.gov.tw
.northguan-nsa.gov.tw
.npm.gov.tw
.nstm.gov.tw
.ntdmh.gov.tw
.ntl.gov.tw
.ntsec.gov.tw
.ntuh.gov.tw
.nvri.gov.tw
.openwrt.org.cn
.penghu-nsa.gov.tw
.post.gov.tw
.qq.com
.redirector.gvt1.com
.safebrowsing.googleapis.com
.simplecd.me
.sina.cn
.sina.com.cn
.siraya-nsa.gov.tw
.site.locql.com
.so.com
.sogou.com
.soso.com
.ssl.gstatic.com
.static.soup.io
.static.typepad.com
.stdtime.gov.tw
.storage.googleapis.com
.sunmoonlake.gov.tw
.taitung-house.gov.tw
.taoyuan.gov.tw
.tax.nat.gov.tw
.tools.google.com
.tpde.aide.gov.tw
.tphcc.gov.tw
.translate.googleapis.com
.trimt-nsa.gov.tw
.uluai.com.cn
.update.googleapis.com
.v6.facebook.com
.vghks.gov.tw
.vghtc.gov.tw
.vghtpe.gov.tw
.vpser.net
.wallproxy.com.cn
.wanfang.gov.tw
.weibo.com
.www.exblog.jp
.www.kodingen.com
.www.typepad.com
.yahoo.cn
.yatsen.gov.tw
.yda.gov.tw
.youdao.com
.zhongsou.com
blog.ontrac.com:80
cdn.ampproject.org:443
cdn.v2ex.com:80
cn.v2ex.com:80
hk.v2ex.com:80
i.v2ex.com:80
ime.baidu.jp:80
lax.v2ex.com:80
neue.v2ex.com:80
nrch.culture.tw:80
pagespeed.v2ex.com:80
share.dmhy.org:443
static.v2ex.com:80
store.sprite.org:80
translate.google.cn:80
v2ex.com:80
workspace.v2ex.com:80
www.ampproject.org:443
www.lightnovel.cn:443
www.v2ex.com:80
xx.wwwhost.biz:80
